(function () {
    'use strict';
    window.fallbackCountrySubgenres = {
        early_country_roots: [
            'The Carter Family | Wildwood Flower',
            'The Carter Family | Can the Circle Be Unbroken',
            'Jimmie Rodgers | Blue Yodel No 1',
            'Jimmie Rodgers | Waiting for a Train',
            'Hank Williams | Im So Lonesome I Could Cry',
            'Hank Williams | Your Cheatin Heart',
            'Hank Williams | Hey Good Lookin',
            'Lefty Frizzell | Long Black Veil',
            'Lefty Frizzell | If Youve Got the Money',
            'Ernest Tubb | Walking the Floor over You',
            'Kitty Wells | It Wasnt God Who Made Honky Tonk Angels',
            'Bob Wills | Faded Love',
            'Bob Wills | San Antonio Rose',
            'Merle Travis | Sixteen Tons',
            'Patsy Cline | Crazy',
            'Patsy Cline | Walkin After Midnight',
            'Hank Snow | Im Moving On',
            'Webb Pierce | In the Jailhouse Now'
        ],
        honky_tonk_traditional: [
            'George Jones | He Stopped Loving Her Today',
            'George Jones | The Grand Tour',
            'George Jones | White Lightning',
            'Ray Price | Heartaches by the Number',
            'Ray Price | For the Good Times',
            'Kitty Wells | Making Believe',
            'Ferlin Husky | Wings of a Dove',
            'Faron Young | Hello Walls',
            'Conway Twitty | Hello Darlin',
            'Tammy Wynette | Stand by Your Man',
            'Tammy Wynette | D-I-V-O-R-C-E',
            'Loretta Lynn | Coal Miners Daughter',
            'Loretta Lynn | You Aint Woman Enough',
            'Porter Wagoner | A Satisfied Mind',
            'Buck Owens | Act Naturally',
            'Buck Owens | Tiger by the Tail'
        ],
        outlaw_country: [
            'Willie Nelson | Blue Eyes Crying in the Rain',
            'Willie Nelson | On the Road Again',
            'Willie Nelson | Whiskey River',
            'Waylon Jennings | Luckenbach Texas',
            'Waylon Jennings | Mamas Dont Let Your Babies Grow Up to Be Cowboys',
            'Johnny Cash | Folsom Prison Blues',
            'Johnny Cash | Ring of Fire',
            'Johnny Cash | I Walk the Line',
            'Johnny Cash | Hurt',
            'Kris Kristofferson | Sunday Mornin Comin Down',
            'Kris Kristofferson | Me and Bobby McGee',
            'Townes Van Zandt | Pancho and Lefty',
            'Townes Van Zandt | Waitin Around to Die',
            'Merle Haggard | Mama Tried',
            'Merle Haggard | Okie from Muskogee',
            'David Allan Coe | Would You Lay with Me',
            'Jessi Colter | Im Not Lisa',
            'Billy Joe Shaver | Georgia on a Fast Train'
        ],
        country_folk_singer_songwriter: [
            'John Prine | Angel from Montgomery',
            'John Prine | Sam Stone',
            'John Prine | In Spite of Ourselves',
            'Emmylou Harris | Boulder to Birmingham',
            'Emmylou Harris | Wrecking Ball',
            'Guy Clark | Desperados Waiting for a Train',
            'Guy Clark | L.A. Freeway',
            'Lucinda Williams | Car Wheels on a Gravel Road',
            'Lucinda Williams | Passionate Kisses',
            'Gillian Welch | Look at Miss Ohio',
            'Gillian Welch | Elvis Presley Blues',
            'Gram Parsons | Brass Buttons',
            'Gram Parsons | Return of the Grievous Angel',
            'Nanci Griffith | Love at the Five and Dime',
            'Iris DeMent | Our Town',
            'Steve Earle | Copperhead Road',
            'Steve Earle | Guitar Town',
            'Blaze Foley | Clay Pigeons'
        ],
        neotraditional_80s_90s: [
            'George Strait | Amarillo by Morning',
            'George Strait | The Chair',
            'George Strait | Check Yes or No',
            'Randy Travis | Forever and Ever Amen',
            'Randy Travis | Diggin Up Bones',
            'Reba McEntire | Fancy',
            'Reba McEntire | Does He Love You',
            'Alan Jackson | Chattahoochee',
            'Alan Jackson | Drive',
            'Dwight Yoakam | Guitars Cadillacs',
            'Dwight Yoakam | Honky Tonk Man',
            'Clint Black | Killin Time',
            'Clint Black | A Better Man',
            'Patty Loveless | How Can I Help You Say Goodbye',
            'Travis Tritt | Help Me Hold On',
            'Travis Tritt | Its a Great Day to Be Alive',
            'Vince Gill | When I Call Your Name',
            'Brooks and Dunn | Neon Moon'
        ],
        '90s_2000s_mainstream': [
            'Garth Brooks | Friends in Low Places',
            'Garth Brooks | The Dance',
            'Garth Brooks | Thunder Rolls',
            'Shania Twain | Youre Still the One',
            'Shania Twain | Man I Feel Like a Woman',
            'Shania Twain | That Dont Impress Me Much',
            'Faith Hill | Breathe',
            'Faith Hill | This Kiss',
            'Tim McGraw | Dont Take the Girl',
            'Tim McGraw | Live Like You Were Dying',
            'Dixie Chicks | Wide Open Spaces',
            'Dixie Chicks | Travelin Soldier',
            'Brooks and Dunn | Neon Moon',
            'Brooks and Dunn | Boot Scootin Boogie',
            'Kenny Chesney | The Good Stuff',
            'Kenny Chesney | No Shoes No Shirt No Problems',
            'Toby Keith | Shouldve Been a Cowboy',
            'Toby Keith | Beer for My Horses',
            'Brad Paisley | Mud on the Tires',
            'Keith Urban | Somebody Like You'
        ],
        alt_country_americana: [
            'Uncle Tupelo | No Depression',
            'Uncle Tupelo | New Madrid',
            'Wilco | Box Full of Letters',
            'Wilco | Jesus Etc',
            'Wilco | Impossible Germany',
            'Son Volt | Windfall',
            'Son Volt | Drown',
            'Drive-By Truckers | Decoration Day',
            'Drive-By Truckers | Outfit',
            'Ryan Adams | New York New York',
            'Ryan Adams | Come Pick Me Up',
            'The Jayhawks | Blue',
            'The Jayhawks | Waiting for the Sun',
            'Old Crow Medicine Show | Wagon Wheel',
            'The Avett Brothers | I and Love and You',
            'The Avett Brothers | Head Full of Doubt',
            'Jason Isbell | Cover Me Up',
            'Jason Isbell | Elephant',
            'Tyler Childers | Feathered Indians',
            'Sturgill Simpson | Turtles All the Way Down'
        ],
        modern_country_pop_crossover: [
            'Kacey Musgraves | Slow Burn',
            'Kacey Musgraves | Follow Your Arrow',
            'Kacey Musgraves | Space Cowboy',
            'Chris Stapleton | Tennessee Whiskey',
            'Chris Stapleton | Broken Halos',
            'Maren Morris | My Church',
            'Maren Morris | The Bones',
            'Luke Combs | Beautiful Crazy',
            'Luke Combs | When It Rains It Pours',
            'Zach Bryan | Something in the Orange',
            'Zach Bryan | Heading South',
            'Morgan Wallen | Whiskey Glasses',
            'Morgan Wallen | Last Night',
            'Luke Bryan | Country Girl Shake It for Me',
            'Luke Bryan | Play It Again',
            'Carrie Underwood | Before He Cheats',
            'Miranda Lambert | The House That Built Me',
            'Miranda Lambert | Gunpowder and Lead',
            'Eric Church | Springsteen',
            'Thomas Rhett | Die a Happy Man'
        ]
    };
    window.genreCountryLists = {
        beginner: [
            'Johnny Cash | Ring of Fire',
            'Dolly Parton | Jolene',
            'John Denver | Take Me Home Country Roads',
            'Kenny Rogers | The Gambler',
            'Willie Nelson | On the Road Again',
            'Glen Campbell | Rhinestone Cowboy',
            'Garth Brooks | Friends in Low Places',
            'Shania Twain | Man I Feel Like a Woman',
            'Tim McGraw | Live Like You Were Dying',
            'Carrie Underwood | Before He Cheats',
            'Hank Williams | Your Cheatin Heart',
            'Patsy Cline | Crazy',
            'Johnny Cash | I Walk the Line',
            'Tammy Wynette | Stand by Your Man',
            'Loretta Lynn | Coal Miners Daughter',
            'George Strait | Amarillo by Morning',
            'Alan Jackson | Chattahoochee',
            'Faith Hill | Breathe',
            'Chris Stapleton | Tennessee Whiskey',
            'Luke Combs | Beautiful Crazy',
            'Zach Bryan | Something in the Orange',
            'Dixie Chicks | Wide Open Spaces',
            'Brad Paisley | Mud on the Tires',
            'Keith Urban | Somebody Like You',
            'Miranda Lambert | The House That Built Me'
        ],
        intermediate: [
            'Emmylou Harris | Boulder to Birmingham',
            'Gram Parsons | Return of the Grievous Angel',
            'Lucinda Williams | Car Wheels on a Gravel Road',
            'Gillian Welch | Look at Miss Ohio',
            'Steve Earle | Copperhead Road',
            'Merle Haggard | Mama Tried',
            'George Jones | He Stopped Loving Her Today',
            'Buck Owens | Act Naturally',
            'Dwight Yoakam | Guitars Cadillacs',
            'Jason Isbell | Cover Me Up',
            'Tyler Childers | Feathered Indians',
            'Sturgill Simpson | Turtles All the Way Down',
            'Kacey Musgraves | Follow Your Arrow',
            'Wilco | Jesus Etc',
            'Ryan Adams | New York New York',
            'Drive-By Truckers | Decoration Day',
            'The Avett Brothers | I and Love and You',
            'Old Crow Medicine Show | Wagon Wheel',
            'Randy Travis | Forever and Ever Amen',
            'Reba McEntire | Fancy',
            'Conway Twitty | Hello Darlin',
            'Waylon Jennings | Luckenbach Texas',
            'Kris Kristofferson | Me and Bobby McGee',
            'John Prine | Angel from Montgomery',
            'Eric Church | Springsteen'
        ],
        expert: [
            'Townes Van Zandt | Pancho and Lefty',
            'Townes Van Zandt | Waitin Around to Die',
            'Guy Clark | L.A. Freeway',
            'Guy Clark | Desperados Waiting for a Train',
            'Blaze Foley | Clay Pigeons',
            'John Prine | Sam Stone',
            'John Prine | In Spite of Ourselves',
            'Iris DeMent | Our Town',
            'Nanci Griffith | Love at the Five and Dime',
            'Billy Joe Shaver | Georgia on a Fast Train',
            'Uncle Tupelo | No Depression',
            'Son Volt | Windfall',
            'The Jayhawks | Blue',
            'Jimmie Rodgers | Blue Yodel No 1',
            'The Carter Family | Wildwood Flower',
            'Bob Wills | San Antonio Rose',
            'Lefty Frizzell | Long Black Veil',
            'Porter Wagoner | A Satisfied Mind',
            'Hank Snow | Im Moving On',
            'Ray Price | For the Good Times',
            'Gillian Welch | Elvis Presley Blues',
            'Lucinda Williams | Passionate Kisses',
            'Jason Isbell | Elephant',
            'Tyler Childers | Feathered Indians',
            'Sturgill Simpson | Turtles All the Way Down'
        ]
    };
})();
