(function () {
    'use strict';
    window.fallbackElectronicSubgenres = {
        pioneers_70s_80s: [
            'Kraftwerk | Autobahn',
            'Kraftwerk | The Model',
            'Kraftwerk | Trans-Europe Express',
            'Giorgio Moroder | Chase',
            'Jean-Michel Jarre | Oxygene Part IV',
            'Tangerine Dream | Love on a Real Train',
            'Vangelis | Chariots of Fire',
            'Yellow Magic Orchestra | Rydeen',
            'Gary Numan | Cars',
            'Art of Noise | Close to the Edit',
            'Depeche Mode | Just Cant Get Enough',
            'New Order | Blue Monday'
        ],
        house_classics: [
            'Frankie Knuckles | Your Love',
            'Marshall Jefferson | Move Your Body',
            'Mr Fingers | Can You Feel It',
            'Inner City | Big Fun',
            'Robin S | Show Me Love',
            'Crystal Waters | Gypsy Woman',
            'CeCe Peniston | Finally',
            'Armand Van Helden | You Dont Know Me',
            'Basement Jaxx | Red Alert',
            'Basement Jaxx | Wheres Your Head At',
            'Cassius | 1999',
            'Bob Sinclar | Love Generation',
            'Stardust | Music Sounds Better with You',
            'Modjo | Lady',
            'Spiller | Groovejet'
        ],
        techno_rave_90s: [
            'The Prodigy | Firestarter',
            'The Prodigy | Breathe',
            'The Prodigy | Out of Space',
            'Chemical Brothers | Block Rockin Beats',
            'Chemical Brothers | Setting Sun',
            'Fatboy Slim | Praise You',
            'Fatboy Slim | Right Here Right Now',
            'Underworld | Born Slippy',
            'Orbital | Chime',
            'Orbital | Halcyon',
            'Leftfield | Phat Planet',
            'Faithless | Insomnia',
            'Faithless | God Is a DJ',
            'Roni Size | Brown Paper Bag',
            'The Shamen | Ebeneezer Goode'
        ],
        trip_hop_downtempo: [
            'Massive Attack | Teardrop',
            'Massive Attack | Unfinished Sympathy',
            'Massive Attack | Angel',
            'Portishead | Glory Box',
            'Portishead | Sour Times',
            'Tricky | Black Steel',
            'Tricky | Hell Is Round the Corner',
            'Morcheeba | The Sea',
            'DJ Shadow | Building Steam with a Grain of Salt',
            'UNKLE | Rabbit in Your Headlights',
            'Bonobo | Black Sands',
            'Zero 7 | Destiny',
            'Air | Sexy Boy',
            'Air | Cherry Blossom Girl',
            'Thievery Corporation | Lebanese Blonde'
        ],
        idm_experimental: [
            'Aphex Twin | Windowlicker',
            'Aphex Twin | Xtal',
            'Aphex Twin | Avril 14th',
            'Boards of Canada | Roygbiv',
            'Boards of Canada | Dayvan Cowboy',
            'Autechre | Gantz Graf',
            'Squarepusher | My Red Hot Car',
            'Four Tet | She Moves She',
            'Four Tet | Angel Echoes',
            'Flying Lotus | Never Catch Me',
            'Amon Tobin | Four Ton Mantis',
            'Clark | Winter Linn',
            'Jon Hopkins | Open Eye Signal',
            'Burial | Archangel',
            'Burial | Untrue'
        ],
        french_touch_nu_disco: [
            'Daft Punk | Around the World',
            'Daft Punk | One More Time',
            'Daft Punk | Da Funk',
            'Daft Punk | Get Lucky',
            'Justice | D.A.N.C.E.',
            'Justice | Genesis',
            'Kavinsky | Nightcall',
            'Breakbot | Baby Im Yours',
            'Todd Terje | Inspector Norse',
            'Royksopp | Eple',
            'Royksopp | What Else Is There',
            'Digitalism | Pogo',
            'Simian Mobile Disco | I Believe',
            'Cassius | I Love U So'
        ],
        modern_electronic_2010s_2020s: [
            'Disclosure | Latch',
            'Disclosure | White Noise',
            'Flume | Never Be Like You',
            'Flume | Holdin On',
            'Jamie xx | Gosh',
            'Jamie xx | Loud Places',
            'Caribou | Cant Do Without You',
            'Caribou | Odessa',
            'Kaytranada | Glowed Up',
            'ODESZA | A Moment Apart',
            'Rufus Du Sol | Innerbloom',
            'Bicep | Glue',
            'Bicep | Atlas',
            'Fred Again | Marea',
            'Peggy Gou | Starry Night',
            'Overmono | So U Kno',
            'Skrillex | Scary Monsters and Nice Sprites',
            'Deadmau5 | Strobe',
            'Ross from Friends | Talk to Me Youll Understand',
            'Mall Grab | Cant Get Enough'
        ]
    };
    window.genreElectronicLists = {
        beginner: [
            'Daft Punk | Around the World',
            'Daft Punk | One More Time',
            'Daft Punk | Get Lucky',
            'The Prodigy | Firestarter',
            'Fatboy Slim | Praise You',
            'Chemical Brothers | Block Rockin Beats',
            'Faithless | Insomnia',
            'Underworld | Born Slippy',
            'Massive Attack | Teardrop',
            'Kraftwerk | The Model',
            'Robin S | Show Me Love',
            'Gary Numan | Cars',
            'New Order | Blue Monday',
            'Depeche Mode | Just Cant Get Enough',
            'Moby | Porcelain',
            'Eiffel 65 | Blue',
            'Robert Miles | Children',
            'Basement Jaxx | Red Alert',
            'Deadmau5 | Strobe',
            'Skrillex | Bangarang',
            'Calvin Harris | Summer',
            'Avicii | Levels',
            'David Guetta | Titanium',
            'Disclosure | Latch',
            'Kavinsky | Nightcall'
        ],
        intermediate: [
            'Portishead | Glory Box',
            'Orbital | Chime',
            'Air | Sexy Boy',
            'Royksopp | Eple',
            'Justice | D.A.N.C.E.',
            'Stardust | Music Sounds Better with You',
            'Leftfield | Phat Planet',
            'Flume | Never Be Like You',
            'Caribou | Cant Do Without You',
            'Jamie xx | Gosh',
            'Bonobo | Black Sands',
            'DJ Shadow | Building Steam with a Grain of Salt',
            'Mr Fingers | Can You Feel It',
            'Modjo | Lady',
            'Bicep | Glue',
            'Rufus Du Sol | Innerbloom',
            'Todd Terje | Inspector Norse',
            'Fred Again | Marea',
            'ODESZA | A Moment Apart',
            'Roni Size | Brown Paper Bag',
            'Tricky | Black Steel',
            'Groove Armada | Superstylin',
            'LCD Soundsystem | Daft Punk Is Playing at My House',
            'Hot Chip | Over and Over',
            'Simian Mobile Disco | I Believe'
        ],
        expert: [
            'Aphex Twin | Windowlicker',
            'Aphex Twin | Xtal',
            'Boards of Canada | Roygbiv',
            'Autechre | Gantz Graf',
            'Squarepusher | My Red Hot Car',
            'Four Tet | She Moves She',
            'Flying Lotus | Never Catch Me',
            'Burial | Archangel',
            'Jon Hopkins | Open Eye Signal',
            'Clark | Winter Linn',
            'Amon Tobin | Four Ton Mantis',
            'Overmono | So U Kno',
            'Ross from Friends | Talk to Me Youll Understand',
            'Peggy Gou | Starry Night',
            'Kaytranada | Glowed Up',
            'Mall Grab | Cant Get Enough',
            'Floating Points | Silhouettes',
            'Nathan Fake | The Sky Was Pink',
            'Pantha du Prince | Stick to My Side',
            'Andy Stott | Numb',
            'Actress | Maze',
            'Objekt | Theme from Q',
            'Laurel Halo | Chance of Rain',
            'Holly Herndon | Chorus',
            'Arca | Nonbinary'
        ]
    };
})();
