(function () {
    'use strict';
    window.fallbackHiphopSubgenres = {
        old_school_80s: [
            'Grandmaster Flash | The Message',
            'Run DMC | Its Tricky',
            'Run DMC | Walk This Way',
            'Beastie Boys | Fight for Your Right',
            'Beastie Boys | Paul Revere',
            'LL Cool J | Rock the Bells',
            'LL Cool J | I Need Love',
            'Salt-N-Pepa | Push It',
            'Eric B and Rakim | Paid in Full',
            'Slick Rick | Childrens Story',
            'Doug E. Fresh | The Show',
            'EPMD | Strictly Business'
        ],
        golden_age_90s: [
            'Public Enemy | Fight the Power',
            'Public Enemy | Bring the Noise',
            'A Tribe Called Quest | Can I Kick It',
            'A Tribe Called Quest | Electric Relaxation',
            'De La Soul | Me Myself and I',
            'Wu-Tang Clan | C.R.E.A.M.',
            'Wu-Tang Clan | Protect Ya Neck',
            'Nas | NY State of Mind',
            'Nas | The World Is Yours',
            'Notorious B.I.G. | Juicy',
            'Notorious B.I.G. | Big Poppa',
            'Tupac | California Love',
            'Tupac | Dear Mama',
            'Mobb Deep | Shook Ones Part II',
            'GZA | Liquid Swords',
            'Raekwon | Ice Cream'
        ],
        west_coast_g_funk: [
            'Dr. Dre | Still D.R.E.',
            'Dr. Dre | Nuthin but a G Thang',
            'Snoop Dogg | Gin and Juice',
            'Snoop Dogg | Drop It Like Its Hot',
            'Ice Cube | It Was a Good Day',
            'Ice Cube | Check Yo Self',
            'Cypress Hill | Insane in the Brain',
            'Warren G | Regulate',
            'Coolio | Gangstas Paradise',
            'DJ Quik | Tonite',
            'The Pharcyde | Passin Me By',
            'Nate Dogg | Nobody Does It Better'
        ],
        late_90s_2000s: [
            'Lauryn Hill | Doo Wop That Thing',
            'Fugees | Killing Me Softly',
            'OutKast | Rosa Parks',
            'OutKast | Hey Ya',
            'OutKast | B.O.B.',
            'Eminem | Lose Yourself',
            'Eminem | The Real Slim Shady',
            'Eminem | Stan',
            'Jay-Z | Hard Knock Life',
            'Jay-Z | 99 Problems',
            'DMX | Ruff Ryders Anthem',
            'Missy Elliott | Get Ur Freak On',
            'Missy Elliott | Work It',
            'Lil Kim | Crush on You',
            'Eve | Let Me Blow Ya Mind',
            'Ludacris | Southern Hospitality',
            'Nelly | Hot in Herre',
            'Busta Rhymes | Break Ya Neck'
        ],
        conscious_alternative: [
            'Mos Def | Mathematics',
            'Talib Kweli | Get By',
            'Common | The Light',
            'The Roots | The Seed 2.0',
            'The Roots | You Got Me',
            'Blackstar | Definition',
            'Jurassic 5 | Concrete Schoolyard',
            'Dilated Peoples | Worst Comes to Worst',
            'Atmosphere | Sunshine',
            'Aesop Rock | None Shall Pass',
            'MF DOOM | Rapp Snitch Knishes',
            'MF DOOM | Accordion',
            'Madvillain | All Caps',
            'Deltron 3030 | Mastermind'
        ],
        modern_hiphop_2010s: [
            'Kendrick Lamar | HUMBLE.',
            'Kendrick Lamar | Swimming Pools',
            'Kendrick Lamar | Alright',
            'Drake | Hotline Bling',
            'Drake | Started from the Bottom',
            'J. Cole | No Role Modelz',
            'J. Cole | Middle Child',
            'Kanye West | Stronger',
            'Kanye West | Gold Digger',
            'Kanye West | Black Skinhead',
            'Childish Gambino | This Is America',
            'Childish Gambino | Redbone',
            'Chance the Rapper | Cocoa Butter Kisses',
            'Tyler the Creator | Earfquake',
            'Tyler the Creator | See You Again',
            'Vince Staples | Norf Norf',
            'Denzel Curry | Clout Cobain',
            'Pusha T | Numbers on the Boards'
        ],
        trap_modern_2020s: [
            'Travis Scott | SICKO MODE',
            'Travis Scott | Goosebumps',
            'Megan Thee Stallion | Savage',
            'Cardi B | Bodak Yellow',
            'Lil Nas X | Old Town Road',
            'Doja Cat | Say So',
            'Future | Mask Off',
            'Lil Uzi Vert | XO Tour Llif3',
            'Pop Smoke | Dior',
            'JID | Surround Sound',
            'Little Simz | Introvert',
            'Stormzy | Shut Up',
            'Dave | Streatham',
            'Slowthai | Doorman',
            'Baby Keem | Family Ties',
            'GloRilla | F.N.F.'
        ],
        international_hiphop: [
            'MC Solaar | Bouge de la',
            'IAM | Je danse le MIA',
            'Cro | Easy',
            'Sido | Mein Block',
            'Haftbefehl | Chabos wissen wer der Babo ist',
            'Apache 207 | Roller',
            'Capital Bra | Cherry Lady',
            'Skepta | Shutdown',
            'Dizzee Rascal | Fix Up Look Sharp',
            'Wiley | Wearing My Rolex',
            'Stromae | Alors on danse',
            'OrelSan | Basique'
        ]
    };
    window.genreHiphopLists = {
        beginner: [
            'Eminem | Lose Yourself',
            'Dr. Dre | Still D.R.E.',
            'Notorious B.I.G. | Juicy',
            'Tupac | California Love',
            'Snoop Dogg | Drop It Like Its Hot',
            'OutKast | Hey Ya',
            'Jay-Z | 99 Problems',
            'Kanye West | Stronger',
            'Kanye West | Gold Digger',
            'Drake | Hotline Bling',
            'Kendrick Lamar | HUMBLE.',
            'Coolio | Gangstas Paradise',
            'Nelly | Hot in Herre',
            'Missy Elliott | Get Ur Freak On',
            'Run DMC | Its Tricky',
            'Beastie Boys | Fight for Your Right',
            'Ice Cube | It Was a Good Day',
            'Lauryn Hill | Doo Wop That Thing',
            'Childish Gambino | This Is America',
            'Lil Nas X | Old Town Road',
            'Travis Scott | SICKO MODE',
            'Cardi B | Bodak Yellow',
            'Salt-N-Pepa | Push It',
            'Will Smith | Gettin Jiggy wit It',
            'Cypress Hill | Insane in the Brain'
        ],
        intermediate: [
            'Nas | NY State of Mind',
            'Wu-Tang Clan | C.R.E.A.M.',
            'A Tribe Called Quest | Can I Kick It',
            'Mobb Deep | Shook Ones Part II',
            'The Roots | The Seed 2.0',
            'OutKast | B.O.B.',
            'Fugees | Killing Me Softly',
            'Kendrick Lamar | Swimming Pools',
            'J. Cole | No Role Modelz',
            'Tyler the Creator | Earfquake',
            'Childish Gambino | Redbone',
            'DMX | Ruff Ryders Anthem',
            'Busta Rhymes | Break Ya Neck',
            'Lil Wayne | A Milli',
            'Eric B and Rakim | Paid in Full',
            'De La Soul | Me Myself and I',
            'Warren G | Regulate',
            'Missy Elliott | Work It',
            'Vince Staples | Norf Norf',
            'Pop Smoke | Dior',
            'Little Simz | Introvert',
            'Denzel Curry | Clout Cobain',
            'Common | The Light',
            'Mos Def | Mathematics',
            'Lil Kim | Crush on You'
        ],
        expert: [
            'GZA | Liquid Swords',
            'Raekwon | Ice Cream',
            'MF DOOM | Rapp Snitch Knishes',
            'Madvillain | All Caps',
            'Deltron 3030 | Mastermind',
            'Aesop Rock | None Shall Pass',
            'Slick Rick | Childrens Story',
            'Big L | Put It On',
            'Organized Konfusion | Stress',
            'Company Flow | End to End Burners',
            'Blackstar | Definition',
            'El-P | Deep Space 9mm',
            'Souls of Mischief | 93 Til Infinity',
            'Dilated Peoples | Worst Comes to Worst',
            'Jurassic 5 | Concrete Schoolyard',
            'Atmosphere | Sunshine',
            'Earl Sweatshirt | Grief',
            'JPEGMAFIA | Baby Im Bleeding',
            'Danny Brown | Aint It Funny',
            'Clipping | Work Work',
            'Ka | I Love',
            'Billy Woods | Checkpoints',
            'Czarface | Cement 3s',
            'Kool Keith | Blue Flowers',
            'The Pharcyde | Passin Me By'
        ]
    };
})();
