(function () {
    'use strict';
    window.fallbackIndieSubgenres = {
        post_punk_indie_roots: [
            'Joy Division | Disorder',
            'Joy Division | Love Will Tear Us Apart',
            'The Cure | A Forest',
            'The Cure | Boys Dont Cry',
            'Wire | Outdoor Miner',
            'Wire | Pink Flag',
            'The Fall | Totally Wired',
            'The Fall | How I Wrote Elastic Man',
            'Echo and the Bunnymen | The Cutter',
            'Echo and the Bunnymen | The Killing Moon',
            'Siouxsie and the Banshees | Hong Kong Garden',
            'Siouxsie and the Banshees | Cities in Dust',
            'New Order | Ceremony',
            'New Order | Bizarre Love Triangle',
            'Orange Juice | Rip It Up',
            'The Jesus and Mary Chain | Just Like Honey',
            'Cocteau Twins | Cherry-Coloured Funk',
            'Cocteau Twins | Pearly-Dewdrops Drops'
        ],
        indie_80s_underground: [
            'The Smiths | This Charming Man',
            'The Smiths | How Soon Is Now',
            'The Smiths | There Is a Light That Never Goes Out',
            'The Replacements | Unsatisfied',
            'The Replacements | Left of the Dial',
            'The Replacements | Bastards of Young',
            'Husker Du | Celebrated Summer',
            'Husker Du | Makes No Sense at All',
            'Sonic Youth | Teenage Riot',
            'Sonic Youth | Schizophrenia',
            'Dinosaur Jr | Freak Scene',
            'Dinosaur Jr | Feel the Pain',
            'Pixies | Where Is My Mind',
            'Pixies | Debaser',
            'Pixies | Monkey Gone to Heaven',
            'Throwing Muses | Counting Backwards',
            'Galaxie 500 | Tugboat',
            'R.E.M. | Radio Free Europe',
            'R.E.M. | Losing My Religion'
        ],
        shoegaze: [
            'My Bloody Valentine | Only Shallow',
            'My Bloody Valentine | When You Sleep',
            'My Bloody Valentine | Sometimes',
            'Slowdive | Alison',
            'Slowdive | When the Sun Hits',
            'Slowdive | Sugar for the Pill',
            'Ride | Vapour Trail',
            'Ride | Leave Them All Behind',
            'Lush | Sweetness and Light',
            'Lush | De-Luxe',
            'Chapterhouse | Pearl',
            'Swervedriver | Duel',
            'Catherine Wheel | Black Metallic',
            'Pale Saints | Sight of You',
            'Adorable | Sunshine Smile'
        ],
        indie_90s_canon: [
            'Pavement | Gold Soundz',
            'Pavement | Range Life',
            'Pavement | Cut Your Hair',
            'Radiohead | Fake Plastic Trees',
            'Radiohead | Paranoid Android',
            'Radiohead | No Surprises',
            'The Breeders | Cannonball',
            'The Breeders | Divine Hammer',
            'Neutral Milk Hotel | Holland 1945',
            'Neutral Milk Hotel | In the Aeroplane Over the Sea',
            'Slowdive | When the Sun Hits',
            'Blur | Beetlebum',
            'Blur | Coffee and TV',
            'Weezer | Say It Aint So',
            'Weezer | Buddy Holly',
            'Portishead | Sour Times',
            'Elliott Smith | Between the Bars',
            'Elliott Smith | Waltz No 2',
            'Belle and Sebastian | The Boy with the Arab Strap',
            'Guided by Voices | I Am a Scientist'
        ],
        indie_90s_2000s_transition: [
            'Modest Mouse | Dramamine',
            'Modest Mouse | Float On',
            'Modest Mouse | Trailer Trash',
            'Built to Spill | Carry the Zero',
            'Built to Spill | Goin Against Your Mind',
            'Death Cab for Cutie | Company Calls',
            'Death Cab for Cutie | Soul Meets Body',
            'Death Cab for Cutie | I Will Follow You into the Dark',
            'The Flaming Lips | Race for the Prize',
            'The Flaming Lips | Do You Realize',
            'Yo La Tengo | Autumn Sweater',
            'Yo La Tengo | Tom Courtenay',
            'Mogwai | Mogwai Fear Satan',
            'Mogwai | Take Me Somewhere Nice',
            'Sigur Ros | Svefn g Englar',
            'Sigur Ros | Hoppipolla',
            'Air | Sexy Boy',
            'Spoon | The Way We Get By',
            'Spoon | I Turn My Camera On'
        ],
        indie_2000s_wave: [
            'The Strokes | Someday',
            'The Strokes | Last Nite',
            'The Strokes | Reptilia',
            'Interpol | Obstacle 1',
            'Interpol | Evil',
            'Arcade Fire | Neighborhood 1',
            'Arcade Fire | Wake Up',
            'Arcade Fire | Rebellion Lies',
            'Yeah Yeah Yeahs | Maps',
            'Yeah Yeah Yeahs | Heads Will Roll',
            'The Postal Service | Such Great Heights',
            'Sufjan Stevens | Chicago',
            'Sufjan Stevens | Mystery of Love',
            'Wilco | Jesus Etc',
            'Wilco | I Am Trying to Break Your Heart',
            'LCD Soundsystem | All My Friends',
            'LCD Soundsystem | Daft Punk Is Playing at My House',
            'Bloc Party | Helicopter',
            'Bloc Party | Banquet',
            'Franz Ferdinand | Take Me Out',
            'The Shins | New Slang',
            'The National | Fake Empire',
            'TV on the Radio | Wolf Like Me'
        ],
        indie_2010s_expansion: [
            'Tame Impala | Feels Like We Only Go Backwards',
            'Tame Impala | The Less I Know the Better',
            'Tame Impala | Elephant',
            'Beach House | Space Song',
            'Beach House | Myth',
            'Beach House | Silver Soul',
            'The National | Bloodbuzz Ohio',
            'The National | I Need My Girl',
            'Bon Iver | Skinny Love',
            'Bon Iver | Holocene',
            'Phoebe Bridgers | Motion Sickness',
            'Phoebe Bridgers | Kyoto',
            'Mitski | Nobody',
            'Mitski | Your Best American Girl',
            'Vampire Weekend | Harmony Hall',
            'Vampire Weekend | A-Punk',
            'The War on Drugs | Red Eyes',
            'The War on Drugs | Under the Pressure',
            'Mac DeMarco | Chamber of Reflection',
            'Mac DeMarco | My Old Man',
            'Grizzly Bear | Two Weeks',
            'Fleet Foxes | White Winter Hymnal',
            'Father John Misty | Real Love Baby',
            'Angel Olsen | Shut Up Kiss Me',
            'Snail Mail | Pristine'
        ],
        modern_indie: [
            'Big Thief | Simulation Swarm',
            'Big Thief | Not',
            'Big Thief | Masterpiece',
            'Fontaines DC | Boys in the Better Land',
            'Fontaines DC | I Dont Belong',
            'Alvvays | Dreams Tonite',
            'Alvvays | Archie Marry Me',
            'Black Country New Road | The Place Where He Inserted the Blade',
            'Black Country New Road | Concorde',
            'Wet Leg | Chaise Longue',
            'Wet Leg | Being in Love',
            'Japanese Breakfast | Be Sweet',
            'Japanese Breakfast | Savage Good Boy',
            'Boygenius | Not Strong Enough',
            'Boygenius | True Blue',
            'Idles | Never Fight a Man with a Perm',
            'Idles | Colossus',
            'Black Midi | John L',
            'Black Midi | Welcome to Hell',
            'Dry Cleaning | Scratchcard Lanyard',
            'Squid | Narrator',
            'Wednesday | Bull Believer',
            'Horsegirl | Anti-glory'
        ]
    };
    window.genreIndieLists = {
        beginner: [
            'Nirvana | Smells Like Teen Spirit',
            'Oasis | Wonderwall',
            'Radiohead | Creep',
            'The Killers | Mr. Brightside',
            'Arctic Monkeys | I Bet You Look Good on the Dancefloor',
            'Franz Ferdinand | Take Me Out',
            'The Strokes | Last Nite',
            'R.E.M. | Losing My Religion',
            'The Smiths | There Is a Light That Never Goes Out',
            'The Cure | Boys Dont Cry',
            'Pixies | Where Is My Mind',
            'Blur | Song 2',
            'Weezer | Buddy Holly',
            'Arcade Fire | Wake Up',
            'Tame Impala | The Less I Know the Better',
            'Bon Iver | Skinny Love',
            'Fleet Foxes | White Winter Hymnal',
            'Vampire Weekend | A-Punk',
            'Modest Mouse | Float On',
            'Death Cab for Cutie | I Will Follow You into the Dark',
            'The Postal Service | Such Great Heights',
            'Sigur Ros | Hoppipolla',
            'Phoebe Bridgers | Kyoto',
            'Wet Leg | Chaise Longue',
            'Boygenius | Not Strong Enough'
        ],
        intermediate: [
            'Pavement | Range Life',
            'Built to Spill | Carry the Zero',
            'Modest Mouse | Trailer Trash',
            'The Shins | New Slang',
            'Death Cab for Cutie | Soul Meets Body',
            'Interpol | Obstacle 1',
            'LCD Soundsystem | All My Friends',
            'The National | Bloodbuzz Ohio',
            'Yeah Yeah Yeahs | Maps',
            'Bloc Party | Banquet',
            'TV on the Radio | Wolf Like Me',
            'Beach House | Space Song',
            'Grizzly Bear | Two Weeks',
            'The War on Drugs | Red Eyes',
            'Angel Olsen | Shut Up Kiss Me',
            'Mac DeMarco | Chamber of Reflection',
            'Father John Misty | Real Love Baby',
            'Mitski | Your Best American Girl',
            'Spoon | The Way We Get By',
            'Sufjan Stevens | Chicago',
            'The Flaming Lips | Do You Realize',
            'Wilco | Jesus Etc',
            'Elliott Smith | Between the Bars',
            'Belle and Sebastian | The Boy with the Arab Strap',
            'Fontaines DC | I Dont Belong'
        ],
        expert: [
            'Slint | Good Morning Captain',
            'Slowdive | Alison',
            'My Bloody Valentine | Only Shallow',
            'Ride | Vapour Trail',
            'Cocteau Twins | Cherry-Coloured Funk',
            'The Jesus and Mary Chain | Just Like Honey',
            'Galaxie 500 | Tugboat',
            'The Replacements | Left of the Dial',
            'Husker Du | Makes No Sense at All',
            'Sonic Youth | Teenage Riot',
            'Guided by Voices | I Am a Scientist',
            'Neutral Milk Hotel | Holland 1945',
            'Big Thief | Simulation Swarm',
            'Black Country New Road | Concorde',
            'Black Midi | John L',
            'Dry Cleaning | Scratchcard Lanyard',
            'Squid | Narrator',
            'Wednesday | Bull Believer',
            'Yo La Tengo | Autumn Sweater',
            'Mogwai | Mogwai Fear Satan',
            'Lush | Sweetness and Light',
            'Swervedriver | Duel',
            'Snail Mail | Pristine',
            'Alvvays | Archie Marry Me',
            'Japanese Breakfast | Savage Good Boy'
        ]
    };
})();
