(function () {
    'use strict';
    window.fallbackJazzSubgenres = {
        early_jazz_proto: [
            'Louis Armstrong | West End Blues',
            'Louis Armstrong | What a Wonderful World',
            'Louis Armstrong | Heebie Jeebies',
            'Jelly Roll Morton | Black Bottom Stomp',
            'Jelly Roll Morton | King Porter Stomp',
            'Sidney Bechet | Petite Fleur',
            'Sidney Bechet | Summertime',
            'Bix Beiderbecke | Singin the Blues',
            'King Oliver | Canal Street Blues',
            'Fats Waller | Honeysuckle Rose',
            'Fats Waller | Aint Misbehavin',
            'Earl Hines | Weather Bird',
            'James P Johnson | Carolina Shout',
            'Bessie Smith | St Louis Blues',
            'Django Reinhardt | Minor Swing',
            'Django Reinhardt | Nuages'
        ],
        swing_big_band: [
            'Duke Ellington | Take the A Train',
            'Duke Ellington | It Dont Mean a Thing',
            'Duke Ellington | Mood Indigo',
            'Count Basie | One Oclock Jump',
            'Count Basie | April in Paris',
            'Benny Goodman | Sing Sing Sing',
            'Benny Goodman | Moonglow',
            'Glenn Miller | In the Mood',
            'Glenn Miller | Moonlight Serenade',
            'Artie Shaw | Begin the Beguine',
            'Ella Fitzgerald | A Tisket a Tasket',
            'Ella Fitzgerald | Summertime',
            'Ella Fitzgerald | Dream a Little Dream of Me',
            'Cab Calloway | Minnie the Moocher',
            'Woody Herman | Woodchoppers Ball',
            'Billie Holiday | Strange Fruit',
            'Billie Holiday | God Bless the Child',
            'Sarah Vaughan | Lullaby of Birdland'
        ],
        bebop_hard_bop_roots: [
            'Charlie Parker | Ko Ko',
            'Charlie Parker | Ornithology',
            'Charlie Parker | Confirmation',
            'Dizzy Gillespie | A Night in Tunisia',
            'Dizzy Gillespie | Salt Peanuts',
            'Thelonious Monk | Round Midnight',
            'Thelonious Monk | Straight No Chaser',
            'Thelonious Monk | Blue Monk',
            'Bud Powell | Dance of the Infidels',
            'Bud Powell | Un Poco Loco',
            'Max Roach | Joy Spring',
            'Sonny Rollins | Airegin',
            'Sonny Rollins | St Thomas',
            'Clifford Brown | Joy Spring',
            'Horace Silver | Song for My Father',
            'Horace Silver | The Preacher',
            'Art Blakey | Moanin',
            'Art Blakey | A Night in Tunisia',
            'Cannonball Adderley | Mercy Mercy Mercy'
        ],
        cool_jazz_west_coast: [
            'Miles Davis | So What',
            'Miles Davis | Kind of Blue',
            'Miles Davis | Blue in Green',
            'Dave Brubeck | Take Five',
            'Dave Brubeck | Blue Rondo a la Turk',
            'Chet Baker | My Funny Valentine',
            'Chet Baker | Almost Blue',
            'Chet Baker | Lets Get Lost',
            'Stan Getz | The Girl from Ipanema',
            'Stan Getz | Desafinado',
            'Lennie Tristano | Line Up',
            'Gil Evans | La Nevadan',
            'Paul Desmond | Take Five',
            'Modern Jazz Quartet | Django',
            'Gerry Mulligan | Walkin Shoes',
            'Ahmad Jamal | Poinciana'
        ],
        modal_post_bop: [
            'John Coltrane | Impressions',
            'John Coltrane | A Love Supreme Part I',
            'John Coltrane | My Favorite Things',
            'John Coltrane | Giant Steps',
            'Wayne Shorter | Footprints',
            'Wayne Shorter | Speak No Evil',
            'Herbie Hancock | Maiden Voyage',
            'Herbie Hancock | Cantaloupe Island',
            'McCoy Tyner | Passion Dance',
            'Joe Henderson | Inner Urge',
            'Joe Henderson | Recorda Me',
            'Freddie Hubbard | Red Clay',
            'Eric Dolphy | Out to Lunch',
            'Eric Dolphy | Hat and Beard',
            'Tony Williams | Emergency',
            'Lee Morgan | The Sidewinder',
            'Dexter Gordon | Go',
            'Grant Green | Idle Moments'
        ],
        free_jazz_avantgarde: [
            'Ornette Coleman | Lonely Woman',
            'Ornette Coleman | Free Jazz',
            'Cecil Taylor | Unit Structures',
            'Albert Ayler | Ghosts',
            'Albert Ayler | Spiritual Unity',
            'Sun Ra | Space Is the Place',
            'Sun Ra | Lanquidity',
            'Pharoah Sanders | The Creator Has a Master Plan',
            'Pharoah Sanders | You Gotta Have Freedom',
            'Archie Shepp | Fire Music',
            'Anthony Braxton | Composition 23c',
            'Art Ensemble of Chicago | People in Sorrow',
            'Don Cherry | Brown Rice',
            'Alice Coltrane | Journey in Satchidananda',
            'Peter Brotzmann | Machine Gun'
        ],
        jazz_fusion_electric: [
            'Miles Davis | Bitches Brew',
            'Miles Davis | In a Silent Way',
            'Weather Report | Birdland',
            'Weather Report | Teen Town',
            'Herbie Hancock | Chameleon',
            'Herbie Hancock | Rockit',
            'Return to Forever | Romantic Warrior',
            'Return to Forever | Spain',
            'Mahavishnu Orchestra | Meeting of the Spirits',
            'Mahavishnu Orchestra | Birds of Fire',
            'Tony Williams Lifetime | Emergency',
            'Jeff Beck | Blow by Blow',
            'Pat Metheny | Phase Dance',
            'Pat Metheny | Last Train Home',
            'Chick Corea | Spain',
            'Jaco Pastorius | Portrait of Tracy',
            'Stanley Clarke | School Days',
            'Jean-Luc Ponty | Enigmatic Ocean'
        ],
        spiritual_ethno_jazz: [
            'Pharoah Sanders | Karma',
            'Alice Coltrane | Journey in Satchidananda',
            'Alice Coltrane | Ptah the El Daoud',
            'Don Cherry | Brown Rice',
            'Yusef Lateef | Eastern Sounds',
            'Abdullah Ibrahim | The Wedding',
            'Abdullah Ibrahim | Mannenberg',
            'Lonnie Liston Smith | Expansions',
            'Sun Ra | Lanquidity',
            'Joe Zawinul | In a Silent Way',
            'Mulatu Astatke | Yekermo Sew',
            'Hugh Masekela | Grazing in the Grass',
            'Randy Weston | Blue Moses',
            'Babatunde Olatunji | Jin Go Lo Ba'
        ],
        smooth_crossover: [
            'George Benson | Breezin',
            'George Benson | Give Me the Night',
            'Grover Washington Jr | Just the Two of Us',
            'Bob James | Nautilus',
            'Bob James | Angela',
            'Spyro Gyra | Morning Dance',
            'Lee Ritenour | Rio Funk',
            'David Sanborn | Chicago Song',
            'Ramsey Lewis | Sun Goddess',
            'Chick Corea | Spain',
            'Al Jarreau | Were in This Love Together',
            'Joe Sample | Carmel',
            'Fourplay | After the Dance',
            'Earl Klugh | Living Inside Your Love',
            'Najee | Sweet Love'
        ],
        modern_jazz_acoustic: [
            'Brad Mehldau | Exit Music for a Film',
            'Brad Mehldau | Knives Out',
            'Keith Jarrett | The Koln Concert Part I',
            'Keith Jarrett | My Song',
            'Pat Metheny | Question and Answer',
            'Wynton Marsalis | Black Codes',
            'Charlie Haden | First Song',
            'Joe Lovano | I Want to Talk About You',
            'Fred Hersch | Floating',
            'Joshua Redman | Jazz Crimes',
            'Avishai Cohen | Seattle',
            'Esbjorn Svensson Trio | From Gagarin Point of View',
            'Robert Glasper | Afro Blue',
            'Christian Scott | Isadora',
            'Ambrose Akinmusire | Rollcall for Those Absent'
        ],
        nu_jazz_future_jazz: [
            'The Comet Is Coming | Summon the Fire',
            'The Comet Is Coming | Birth of Creation',
            'BadBadNotGood | Time Moves Slow',
            'BadBadNotGood | Speaking Gently',
            'Makaya McCraven | In the Moment',
            'Kamasi Washington | Truth',
            'Kamasi Washington | Fists of Fury',
            'Sons of Kemet | My Queen Is Ada Eastman',
            'Sons of Kemet | Hustle',
            'Nubya Garcia | Pace',
            'Nubya Garcia | Source',
            'Yussef Dayes | Love Is the Message',
            'Shabaka Hutchings | Black Meditation',
            'GoGo Penguin | Murmuration',
            'Alfa Mist | Door',
            'Ezra Collective | No Confusion',
            'Snarky Puppy | Lingus',
            'Thundercat | Them Changes'
        ]
    };
    window.genreJazzLists = {
        beginner: [
            'Dave Brubeck | Take Five',
            'Louis Armstrong | What a Wonderful World',
            'Ella Fitzgerald | Summertime',
            'Frank Sinatra | Fly Me to the Moon',
            'Miles Davis | So What',
            'Glenn Miller | In the Mood',
            'Nat King Cole | Unforgettable',
            'Duke Ellington | Take the A Train',
            'Billie Holiday | Strange Fruit',
            'Benny Goodman | Sing Sing Sing',
            'George Benson | Give Me the Night',
            'Herbie Hancock | Rockit',
            'Stan Getz | The Girl from Ipanema',
            'Django Reinhardt | Minor Swing',
            'Cab Calloway | Minnie the Moocher',
            'Sarah Vaughan | Lullaby of Birdland',
            'Chet Baker | My Funny Valentine',
            'Nina Simone | Feeling Good',
            'Ramsey Lewis | Sun Goddess',
            'Grover Washington Jr | Just the Two of Us',
            'Norah Jones | Dont Know Why',
            'John Coltrane | My Favorite Things',
            'Bobby McFerrin | Dont Worry Be Happy',
            'Al Jarreau | Were in This Love Together',
            'Ray Charles | Hit the Road Jack'
        ],
        intermediate: [
            'Weather Report | Birdland',
            'Herbie Hancock | Chameleon',
            'Return to Forever | Spain',
            'Mahavishnu Orchestra | Meeting of the Spirits',
            'Stanley Clarke | School Days',
            'Art Blakey | Moanin',
            'Horace Silver | Song for My Father',
            'Cannonball Adderley | Mercy Mercy Mercy',
            'Wayne Shorter | Speak No Evil',
            'Lee Morgan | The Sidewinder',
            'Dexter Gordon | Go',
            'Pat Metheny | Last Train Home',
            'Jaco Pastorius | Portrait of Tracy',
            'Chick Corea | Spain',
            'Sonny Rollins | St Thomas',
            'Thelonious Monk | Round Midnight',
            'Charles Mingus | Moanin',
            'Kamasi Washington | Truth',
            'Robert Glasper | Afro Blue',
            'Snarky Puppy | Lingus',
            'Ahmad Jamal | Poinciana',
            'Brad Mehldau | Exit Music for a Film',
            'Esbjorn Svensson Trio | From Gagarin Point of View',
            'Thundercat | Them Changes',
            'Grant Green | Idle Moments'
        ],
        expert: [
            'Miles Davis | In a Silent Way',
            'Sun Ra | Space Is the Place',
            'Don Cherry | Brown Rice',
            'Pharoah Sanders | The Creator Has a Master Plan',
            'Alice Coltrane | Journey in Satchidananda',
            'Ornette Coleman | Lonely Woman',
            'Eric Dolphy | Out to Lunch',
            'Cecil Taylor | Unit Structures',
            'Albert Ayler | Ghosts',
            'Anthony Braxton | Composition 23c',
            'Mulatu Astatke | Yekermo Sew',
            'Yusef Lateef | Eastern Sounds',
            'Makaya McCraven | In the Moment',
            'Shabaka Hutchings | Black Meditation',
            'BadBadNotGood | Time Moves Slow',
            'Sons of Kemet | Hustle',
            'Nubya Garcia | Pace',
            'GoGo Penguin | Murmuration',
            'Alfa Mist | Door',
            'Peter Brotzmann | Machine Gun',
            'Archie Shepp | Fire Music',
            'Randy Weston | Blue Moses',
            'Abdullah Ibrahim | Mannenberg',
            'Keith Jarrett | My Song',
            'Jean-Luc Ponty | Enigmatic Ocean'
        ]
    };
})();
