(function () {
    'use strict';
    window.fallbackKlassikSubgenres = {
        baroque: [
            'Johann Sebastian Bach | Brandenburg Concerto No 3',
            'Johann Sebastian Bach | Toccata and Fugue in D Minor',
            'Johann Sebastian Bach | Air on the G String',
            'Johann Sebastian Bach | Cello Suite No 1 Prelude',
            'Johann Sebastian Bach | Well-Tempered Clavier Prelude No 1',
            'Antonio Vivaldi | The Four Seasons Spring',
            'Antonio Vivaldi | The Four Seasons Winter',
            'Antonio Vivaldi | The Four Seasons Summer',
            'George Frideric Handel | Water Music',
            'George Frideric Handel | Messiah Hallelujah',
            'George Frideric Handel | Arrival of the Queen of Sheba',
            'Henry Purcell | Music for the Funeral of Queen Mary',
            'Henry Purcell | When I Am Laid in Earth',
            'Jean-Philippe Rameau | Les Indes Galantes',
            'Domenico Scarlatti | Keyboard Sonata K141',
            'Johann Pachelbel | Canon in D',
            'Arcangelo Corelli | Christmas Concerto',
            'Georg Philipp Telemann | Viola Concerto in G Major'
        ],
        classical_era: [
            'Wolfgang Amadeus Mozart | Eine Kleine Nachtmusik',
            'Wolfgang Amadeus Mozart | Symphony No 40',
            'Wolfgang Amadeus Mozart | Piano Concerto No 21',
            'Wolfgang Amadeus Mozart | Requiem Lacrimosa',
            'Wolfgang Amadeus Mozart | The Marriage of Figaro Overture',
            'Wolfgang Amadeus Mozart | Rondo Alla Turca',
            'Joseph Haydn | Symphony No 94 Surprise',
            'Joseph Haydn | Trumpet Concerto in E flat',
            'Joseph Haydn | String Quartet Op 76 Emperor',
            'Ludwig van Beethoven | Symphony No 5',
            'Ludwig van Beethoven | Fur Elise',
            'Ludwig van Beethoven | Moonlight Sonata',
            'Ludwig van Beethoven | Symphony No 9 Ode to Joy',
            'Ludwig van Beethoven | Symphony No 7 Allegretto',
            'Christoph Willibald Gluck | Orfeo ed Euridice Dance of the Blessed Spirits',
            'Luigi Boccherini | Minuet',
            'Antonio Salieri | Sinfonia Veneziana'
        ],
        early_romantic: [
            'Franz Schubert | Unfinished Symphony',
            'Franz Schubert | Ave Maria',
            'Franz Schubert | Erlkonig',
            'Franz Schubert | Trout Quintet',
            'Felix Mendelssohn | Wedding March',
            'Felix Mendelssohn | Violin Concerto in E Minor',
            'Felix Mendelssohn | Hebrides Overture',
            'Robert Schumann | Kinderszenen Traumerai',
            'Robert Schumann | Piano Concerto in A Minor',
            'Carl Maria von Weber | Invitation to the Dance',
            'Niccolo Paganini | Caprice No 24',
            'Hector Berlioz | Symphonie Fantastique',
            'Hector Berlioz | Roman Carnival Overture',
            'Fryderyk Chopin | Nocturne Op 9 No 2',
            'Fryderyk Chopin | Ballade No 1',
            'Fryderyk Chopin | Revolutionary Etude',
            'Fryderyk Chopin | Waltz in C Sharp Minor',
            'Franz Liszt | Hungarian Rhapsody No 2',
            'Franz Liszt | Liebestraum No 3'
        ],
        romantic_late: [
            'Johannes Brahms | Hungarian Dance No 5',
            'Johannes Brahms | Symphony No 4',
            'Johannes Brahms | Violin Concerto in D Major',
            'Richard Wagner | Ride of the Valkyries',
            'Richard Wagner | Tristan und Isolde Prelude',
            'Giuseppe Verdi | Dies Irae Requiem',
            'Giuseppe Verdi | La Traviata Brindisi',
            'Giacomo Puccini | Nessun Dorma',
            'Giacomo Puccini | O Mio Babbino Caro',
            'Peter Ilyich Tchaikovsky | Nutcracker Dance of the Sugar Plum Fairy',
            'Peter Ilyich Tchaikovsky | Swan Lake Theme',
            'Peter Ilyich Tchaikovsky | 1812 Overture',
            'Peter Ilyich Tchaikovsky | Piano Concerto No 1',
            'Antonin Dvorak | Symphony No 9 New World',
            'Antonin Dvorak | Humoresque No 7',
            'Edvard Grieg | Peer Gynt Morning Mood',
            'Edvard Grieg | In the Hall of the Mountain King',
            'Camille Saint-Saens | Danse Macabre',
            'Camille Saint-Saens | The Swan',
            'Nikolai Rimsky-Korsakov | Flight of the Bumblebee',
            'Gustav Mahler | Symphony No 5 Adagietto'
        ],
        impressionism_modernism: [
            'Claude Debussy | Clair de Lune',
            'Claude Debussy | Prelude to the Afternoon of a Faun',
            'Claude Debussy | Arabesque No 1',
            'Claude Debussy | La Mer',
            'Maurice Ravel | Bolero',
            'Maurice Ravel | Pavane for a Dead Princess',
            'Maurice Ravel | Daphnis et Chloe Suite No 2',
            'Erik Satie | Gymnopedie No 1',
            'Erik Satie | Gnossienne No 1',
            'Gabriel Faure | Pavane',
            'Gabriel Faure | Sicilienne',
            'Igor Stravinsky | Rite of Spring',
            'Igor Stravinsky | Firebird Suite Finale',
            'Igor Stravinsky | Petrushka',
            'Arnold Schoenberg | Verklarte Nacht',
            'Ottorino Respighi | Pines of Rome'
        ],
        early_20th_century: [
            'Sergei Rachmaninoff | Piano Concerto No 2',
            'Sergei Rachmaninoff | Rhapsody on a Theme of Paganini',
            'Sergei Rachmaninoff | Vocalise',
            'Sergei Prokofiev | Dance of the Knights',
            'Sergei Prokofiev | Peter and the Wolf',
            'Sergei Prokofiev | Romeo and Juliet',
            'Dmitri Shostakovich | Symphony No 5',
            'Dmitri Shostakovich | Waltz No 2',
            'Dmitri Shostakovich | String Quartet No 8',
            'Bela Bartok | Concerto for Orchestra',
            'Bela Bartok | Music for Strings Percussion and Celesta',
            'Jean Sibelius | Finlandia',
            'Jean Sibelius | Violin Concerto',
            'Leos Janacek | Sinfonietta',
            'Kurt Weill | Mack the Knife',
            'Paul Hindemith | Symphonic Metamorphosis',
            'Gustav Holst | The Planets Mars',
            'Gustav Holst | The Planets Jupiter',
            'Samuel Barber | Adagio for Strings',
            'Aaron Copland | Appalachian Spring'
        ],
        contemporary_classical: [
            'John Cage | 4 33',
            'Philip Glass | Glassworks Opening',
            'Philip Glass | Metamorphosis One',
            'Philip Glass | Einstein on the Beach Knee Play 1',
            'Steve Reich | Music for 18 Musicians',
            'Steve Reich | Electric Counterpoint III',
            'Terry Riley | In C',
            'Arvo Part | Spiegel im Spiegel',
            'Arvo Part | Fratres',
            'Arvo Part | Cantus in Memoriam Benjamin Britten',
            'Henryk Gorecki | Symphony No 3',
            'John Adams | Short Ride in a Fast Machine',
            'John Adams | Shaker Loops',
            'Gyorgy Ligeti | Lux Aeterna',
            'Gyorgy Ligeti | Atmospheres',
            'Krzysztof Penderecki | Threnody for the Victims of Hiroshima',
            'Olivier Messiaen | Quartet for the End of Time'
        ],
        modern_crossover_minimal: [
            'Max Richter | On the Nature of Daylight',
            'Max Richter | November',
            'Max Richter | Spring 1 Recomposed',
            'Nils Frahm | Says',
            'Nils Frahm | All Melody',
            'Johann Johannsson | Flight from the City',
            'Johann Johannsson | The Sun Is Also a Star',
            'Hildur Gudnadottir | Saman',
            'Hildur Gudnadottir | Chernobyl',
            'Olafur Arnalds | Near Light',
            'Olafur Arnalds | Saman',
            'Ludovico Einaudi | Nuvole Bianche',
            'Ludovico Einaudi | Experience',
            'Ludovico Einaudi | Una Mattina',
            'Yann Tiersen | Comptine dun Autre Ete',
            'Michael Nyman | The Heart Asks Pleasure First',
            'Ryuichi Sakamoto | Merry Christmas Mr Lawrence',
            'Dustin O Halloran | We Move Lightly',
            'Joep Beving | Prehension'
        ]
    };
    window.genreKlassikLists = {
        beginner: [
            'Ludwig van Beethoven | Symphony No 5',
            'Wolfgang Amadeus Mozart | Eine Kleine Nachtmusik',
            'Antonio Vivaldi | The Four Seasons Spring',
            'Johann Pachelbel | Canon in D',
            'Peter Ilyich Tchaikovsky | Swan Lake Theme',
            'Johann Sebastian Bach | Air on the G String',
            'George Frideric Handel | Messiah Hallelujah',
            'Ludwig van Beethoven | Fur Elise',
            'Ludwig van Beethoven | Moonlight Sonata',
            'Ludwig van Beethoven | Symphony No 9 Ode to Joy',
            'Fryderyk Chopin | Nocturne Op 9 No 2',
            'Claude Debussy | Clair de Lune',
            'Maurice Ravel | Bolero',
            'Erik Satie | Gymnopedie No 1',
            'Edvard Grieg | In the Hall of the Mountain King',
            'Peter Ilyich Tchaikovsky | Nutcracker Dance of the Sugar Plum Fairy',
            'Giacomo Puccini | Nessun Dorma',
            'Richard Wagner | Ride of the Valkyries',
            'Nikolai Rimsky-Korsakov | Flight of the Bumblebee',
            'Johann Sebastian Bach | Toccata and Fugue in D Minor',
            'Ludovico Einaudi | Nuvole Bianche',
            'Samuel Barber | Adagio for Strings',
            'Gustav Holst | The Planets Jupiter',
            'Sergei Rachmaninoff | Piano Concerto No 2',
            'Yann Tiersen | Comptine dun Autre Ete'
        ],
        intermediate: [
            'Maurice Ravel | Pavane for a Dead Princess',
            'Camille Saint-Saens | Danse Macabre',
            'Gustav Holst | The Planets Mars',
            'Edvard Grieg | Peer Gynt Morning Mood',
            'Antonin Dvorak | Symphony No 9 New World',
            'Franz Schubert | Ave Maria',
            'Felix Mendelssohn | Violin Concerto in E Minor',
            'Johannes Brahms | Hungarian Dance No 5',
            'Sergei Prokofiev | Dance of the Knights',
            'Dmitri Shostakovich | Waltz No 2',
            'Philip Glass | Glassworks Opening',
            'Arvo Part | Spiegel im Spiegel',
            'Max Richter | On the Nature of Daylight',
            'Gustav Mahler | Symphony No 5 Adagietto',
            'Fryderyk Chopin | Ballade No 1',
            'Franz Liszt | Hungarian Rhapsody No 2',
            'Aaron Copland | Appalachian Spring',
            'Igor Stravinsky | Firebird Suite Finale',
            'Jean Sibelius | Finlandia',
            'Nils Frahm | Says',
            'Olafur Arnalds | Near Light',
            'Ryuichi Sakamoto | Merry Christmas Mr Lawrence',
            'Johann Johannsson | Flight from the City',
            'Steve Reich | Music for 18 Musicians',
            'Hector Berlioz | Symphonie Fantastique'
        ],
        expert: [
            'Igor Stravinsky | Rite of Spring',
            'Gyorgy Ligeti | Lux Aeterna',
            'Krzysztof Penderecki | Threnody for the Victims of Hiroshima',
            'Henryk Gorecki | Symphony No 3',
            'Arvo Part | Fratres',
            'Arnold Schoenberg | Verklarte Nacht',
            'Bela Bartok | Music for Strings Percussion and Celesta',
            'Olivier Messiaen | Quartet for the End of Time',
            'Leos Janacek | Sinfonietta',
            'Dmitri Shostakovich | String Quartet No 8',
            'Hildur Gudnadottir | Chernobyl',
            'John Adams | Short Ride in a Fast Machine',
            'Steve Reich | Electric Counterpoint III',
            'Terry Riley | In C',
            'John Cage | 4 33',
            'Gyorgy Ligeti | Atmospheres',
            'Robert Schumann | Piano Concerto in A Minor',
            'Claude Debussy | Prelude to the Afternoon of a Faun',
            'Henry Purcell | When I Am Laid in Earth',
            'Ottorino Respighi | Pines of Rome',
            'Sergei Prokofiev | Romeo and Juliet',
            'Paul Hindemith | Symphonic Metamorphosis',
            'Bela Bartok | Concerto for Orchestra',
            'Richard Wagner | Tristan und Isolde Prelude',
            'Johann Johannsson | The Sun Is Also a Star'
        ]
    };
})();
