(function () {
    'use strict';
    window.fallbackMetalSubgenres = {
        proto_heavy_metal: [
            'Black Sabbath | Paranoid',
            'Black Sabbath | Iron Man',
            'Black Sabbath | War Pigs',
            'Black Sabbath | N.I.B.',
            'Led Zeppelin | Immigrant Song',
            'Led Zeppelin | Whole Lotta Love',
            'Deep Purple | Smoke on the Water',
            'Deep Purple | Highway Star',
            'Deep Purple | Burn',
            'Judas Priest | Breaking the Law',
            'Judas Priest | Living After Midnight',
            'Judas Priest | Painkiller',
            'UFO | Rock Bottom',
            'UFO | Doctor Doctor',
            'Thin Lizzy | Jailbreak',
            'Thin Lizzy | The Boys Are Back in Town',
            'Motorhead | Overkill',
            'Motorhead | Ace of Spades',
            'Scorpions | Rock You Like a Hurricane',
            'Rainbow | Stargazer'
        ],
        nwobhm: [
            'Iron Maiden | Running Free',
            'Iron Maiden | The Trooper',
            'Iron Maiden | Run to the Hills',
            'Iron Maiden | Aces High',
            'Iron Maiden | Fear of the Dark',
            'Saxon | Denim and Leather',
            'Saxon | Wheels of Steel',
            'Diamond Head | Am I Evil',
            'Angel Witch | Angel Witch',
            'Venom | Black Metal',
            'Venom | Welcome to Hell',
            'Def Leppard | Photograph',
            'Def Leppard | Pour Some Sugar on Me',
            'Tigers of Pan Tang | Hellbound',
            'Praying Mantis | Cheetah',
            'Tygers of Pan Tang | Love Potion No 9',
            'Raven | Wiped Out',
            'Girlschool | Race with the Devil'
        ],
        thrash_metal: [
            'Metallica | Whiplash',
            'Metallica | Master of Puppets',
            'Metallica | One',
            'Metallica | Enter Sandman',
            'Metallica | Battery',
            'Slayer | Raining Blood',
            'Slayer | Angel of Death',
            'Slayer | South of Heaven',
            'Megadeth | Peace Sells',
            'Megadeth | Holy Wars',
            'Megadeth | Tornado of Souls',
            'Anthrax | Caught in a Mosh',
            'Anthrax | Madhouse',
            'Exodus | Bonded by Blood',
            'Exodus | Toxic Waltz',
            'Testament | Over the Wall',
            'Testament | Practice What You Preach',
            'Kreator | Pleasure to Kill',
            'Sepultura | Beneath the Remains',
            'Sepultura | Roots Bloody Roots',
            'Overkill | Elimination',
            'Pantera | Walk',
            'Pantera | Cowboys from Hell'
        ],
        death_metal: [
            'Death | Pull the Plug',
            'Death | Crystal Mountain',
            'Death | Lack of Comprehension',
            'Morbid Angel | Chapel of Ghouls',
            'Morbid Angel | Where the Slime Live',
            'Obituary | Slowly We Rot',
            'Obituary | Chopped in Half',
            'Entombed | Left Hand Path',
            'Entombed | Wolverine Blues',
            'Cannibal Corpse | Hammer Smashed Face',
            'Deicide | Dead by Dawn',
            'Carcass | Heartwork',
            'Carcass | Incarnated Solvent Abuse',
            'Autopsy | Severed Survival',
            'Bolt Thrower | Those Once Loyal',
            'Suffocation | Liege of Inveracity',
            'Nile | Lashed to the Slave Stick',
            'At the Gates | Slaughter of the Soul'
        ],
        black_metal: [
            'Mayhem | Freezing Moon',
            'Mayhem | De Mysteriis Dom Sathanas',
            'Burzum | Dunkelheit',
            'Burzum | Jesus Tod',
            'Darkthrone | Transilvanian Hunger',
            'Darkthrone | In the Shadow of the Horns',
            'Emperor | Inno a Satana',
            'Emperor | I Am the Black Wizards',
            'Immortal | At the Heart of Winter',
            'Immortal | Sons of Northern Darkness',
            'Gorgoroth | Funeral Procession',
            'Satyricon | Mother North',
            'Satyricon | K.I.N.G.',
            'Bathory | A Fine Day to Die',
            'Bathory | Enter the Eternal Fire',
            'Enslaved | Isa',
            'Dissection | Night\'s Blood',
            'Mgla | Exercises in Futility VI'
        ],
        doom_sludge_stoner: [
            'Candlemass | Solitude',
            'Candlemass | Mirror Mirror',
            'Saint Vitus | Born Too Late',
            'Sleep | Dragonaut',
            'Sleep | Dopesmoker',
            'Electric Wizard | Dopethrone',
            'Electric Wizard | Funeralopolis',
            'Eyehategod | Dixie Whiskey',
            'Kyuss | Green Machine',
            'Kyuss | Gardenia',
            'Neurosis | Through Silver in Blood',
            'Neurosis | The Doorway',
            'Melvins | Honey Bucket',
            'Melvins | Revolve',
            'Crowbar | All I Had I Gave',
            'Acid Bath | Scream of the Butterfly',
            'Windhand | Woodbine',
            'YOB | Marrow'
        ],
        prog_power_metal: [
            'Dream Theater | Pull Me Under',
            'Dream Theater | Metropolis Part 1',
            'Dream Theater | The Spirit Carries On',
            'Queensryche | Operation Mindcrime',
            'Queensryche | Silent Lucidity',
            'Fates Warning | Eye to Eye',
            'Symphony X | Sea of Lies',
            'Symphony X | Set the World on Fire',
            'Blind Guardian | Mirror Mirror',
            'Blind Guardian | The Bards Song',
            'Helloween | Keeper of the Seven Keys',
            'Helloween | I Want Out',
            'Opeth | Windowpane',
            'Opeth | Blackwater Park',
            'Opeth | Ghost of Perdition',
            'Tool | Schism',
            'Tool | Lateralus',
            'Tool | Sober',
            'Kamelot | Center of the Universe',
            'Nightwish | Nemo'
        ],
        nu_metal_alt_metal: [
            'Korn | Freak on a Leash',
            'Korn | Blind',
            'Korn | Got the Life',
            'Deftones | Change in the House of Flies',
            'Deftones | My Own Summer',
            'Deftones | Digital Bath',
            'Slipknot | Wait and Bleed',
            'Slipknot | Duality',
            'Slipknot | Psychosocial',
            'System of a Down | Chop Suey',
            'System of a Down | Toxicity',
            'System of a Down | B.Y.O.B.',
            'Limp Bizkit | Nookie',
            'Limp Bizkit | Break Stuff',
            'Linkin Park | Crawling',
            'Linkin Park | In the End',
            'Linkin Park | Numb',
            'Disturbed | Down with the Sickness',
            'Faith No More | Epic',
            'Faith No More | Midlife Crisis',
            'Rage Against the Machine | Killing in the Name',
            'Rage Against the Machine | Bulls on Parade'
        ],
        modern_extreme_metal: [
            'Meshuggah | Bleed',
            'Meshuggah | Rational Gaze',
            'Meshuggah | New Millennium Cyanide Christ',
            'Gojira | Flying Whales',
            'Gojira | Stranded',
            'Gojira | Silvera',
            'Mastodon | Oblivion',
            'Mastodon | Blood and Thunder',
            'Mastodon | Curl of the Burl',
            'Behemoth | Ov Fire and the Void',
            'Behemoth | Blow Your Trumpets Gabriel',
            'Lamb of God | Laid to Rest',
            'Lamb of God | Redneck',
            'Between the Buried and Me | Selkies',
            'Deafheaven | Dream House',
            'Deafheaven | Sunbather',
            'Power Trip | Executioners Tax',
            'Knocked Loose | Mistakes Like Fractures',
            'Archspire | Bleed the Future',
            'Rivers of Nihil | Where Owls Know My Name'
        ]
    };
    window.genreMetalLists = {
        beginner: [
            'Metallica | Enter Sandman',
            'Iron Maiden | The Trooper',
            'Black Sabbath | Paranoid',
            'AC/DC | Thunderstruck',
            'Guns N Roses | Welcome to the Jungle',
            'Def Leppard | Pour Some Sugar on Me',
            'Scorpions | Rock You Like a Hurricane',
            'Motorhead | Ace of Spades',
            'Judas Priest | Breaking the Law',
            'Ozzy Osbourne | Crazy Train',
            'Metallica | Nothing Else Matters',
            'Metallica | One',
            'Iron Maiden | Run to the Hills',
            'Deep Purple | Smoke on the Water',
            'Linkin Park | In the End',
            'System of a Down | Chop Suey',
            'Slipknot | Duality',
            'Rage Against the Machine | Killing in the Name',
            'Pantera | Walk',
            'Korn | Freak on a Leash',
            'Disturbed | Down with the Sickness',
            'Led Zeppelin | Immigrant Song',
            'Dio | Holy Diver',
            'Rammstein | Du Hast',
            'Nightwish | Nemo'
        ],
        intermediate: [
            'Faith No More | Epic',
            'Deftones | Change in the House of Flies',
            'Tool | Sober',
            'Mastodon | Blood and Thunder',
            'Gojira | Flying Whales',
            'Opeth | Windowpane',
            'Dream Theater | Pull Me Under',
            'Queensryche | Silent Lucidity',
            'Megadeth | Holy Wars',
            'Slayer | Raining Blood',
            'Sepultura | Roots Bloody Roots',
            'Lamb of God | Laid to Rest',
            'Helloween | I Want Out',
            'Blind Guardian | Mirror Mirror',
            'At the Gates | Slaughter of the Soul',
            'Kyuss | Green Machine',
            'Sleep | Dragonaut',
            'Anthrax | Madhouse',
            'Pantera | Cowboys from Hell',
            'Testament | Practice What You Preach',
            'Iron Maiden | Fear of the Dark',
            'Rainbow | Stargazer',
            'Deafheaven | Dream House',
            'Behemoth | Blow Your Trumpets Gabriel',
            'Carcass | Heartwork'
        ],
        expert: [
            'Meshuggah | Bleed',
            'Meshuggah | Rational Gaze',
            'Gojira | Silvera',
            'Tool | Lateralus',
            'Mastodon | Curl of the Burl',
            'Death | Crystal Mountain',
            'Morbid Angel | Chapel of Ghouls',
            'Entombed | Left Hand Path',
            'Candlemass | Solitude',
            'Neurosis | Through Silver in Blood',
            'Electric Wizard | Funeralopolis',
            'Emperor | I Am the Black Wizards',
            'Darkthrone | Transilvanian Hunger',
            'Bolt Thrower | Those Once Loyal',
            'Obituary | Slowly We Rot',
            'Power Trip | Executioners Tax',
            'Archspire | Bleed the Future',
            'Rivers of Nihil | Where Owls Know My Name',
            'Mgla | Exercises in Futility VI',
            'YOB | Marrow',
            'Acid Bath | Scream of the Butterfly',
            'Dissection | Nights Blood',
            'Suffocation | Liege of Inveracity',
            'Between the Buried and Me | Selkies',
            'Knocked Loose | Mistakes Like Fractures'
        ]
    };
})();
