(function () {
    'use strict';
    window.fallbackPopSubgenres = {
        classic_pop_60s_70s: [
            'The Supremes | You Cant Hurry Love',
            'The Ronettes | Be My Baby',
            'Dusty Springfield | Son of a Preacher Man',
            'The Beach Boys | God Only Knows',
            'Simon & Garfunkel | Bridge over Troubled Water',
            'Elton John | Rocket Man',
            'Elton John | Tiny Dancer',
            'Bee Gees | Stayin Alive',
            'Bee Gees | How Deep Is Your Love',
            'ABBA | Dancing Queen',
            'ABBA | Gimme Gimme Gimme',
            'Carole King | Its Too Late',
            'Stevie Wonder | Superstition',
            'Donna Summer | I Feel Love',
            'Blondie | Heart of Glass'
        ],
        pop_80s: [
            'Michael Jackson | Dont Stop Til You Get Enough',
            'Michael Jackson | Wanna Be Startin Somethin',
            'Madonna | Into the Groove',
            'Madonna | Material Girl',
            'Prince | Kiss',
            'Prince | When Doves Cry',
            'Whitney Houston | How Will I Know',
            'Whitney Houston | Greatest Love of All',
            'George Michael | Faith',
            'George Michael | Careless Whisper',
            'Cyndi Lauper | Girls Just Want to Have Fun',
            'Phil Collins | In the Air Tonight',
            'Tina Turner | Whats Love Got to Do with It',
            'A-ha | Take on Me',
            'Tears for Fears | Everybody Wants to Rule the World',
            'Eurythmics | Sweet Dreams',
            'Duran Duran | Rio',
            'Pet Shop Boys | West End Girls',
            'Culture Club | Karma Chameleon',
            'Hall & Oates | I Cant Go for That'
        ],
        pop_90s: [
            'Britney Spears | Toxic',
            'Britney Spears | Baby One More Time',
            'Backstreet Boys | Everybody',
            'Spice Girls | Wannabe',
            'Janet Jackson | Thats the Way Love Goes',
            'TLC | Waterfalls',
            'TLC | No Scrubs',
            'Destinys Child | Say My Name',
            'Mariah Carey | Fantasy',
            'Mariah Carey | Always Be My Baby',
            'Celine Dion | My Heart Will Go On',
            'Alanis Morissette | You Oughta Know',
            'No Doubt | Dont Speak',
            'Natalie Imbruglia | Torn',
            'Sheryl Crow | All I Wanna Do',
            'Savage Garden | Truly Madly Deeply',
            'Ace of Base | The Sign',
            'Hanson | MMMBop',
            'Robyn | Show Me Love'
        ],
        pop_2000s: [
            'Beyonce | Crazy in Love',
            'Beyonce | Single Ladies',
            'Justin Timberlake | Cry Me a River',
            'Justin Timberlake | Rock Your Body',
            'Rihanna | Umbrella',
            'Rihanna | Dont Stop the Music',
            'Shakira | Hips Dont Lie',
            'Nelly Furtado | Say It Right',
            'Gwen Stefani | Hollaback Girl',
            'Outkast | Hey Ya',
            'Kylie Minogue | Cant Get You out of My Head',
            'Robbie Williams | Feel',
            'Coldplay | Yellow',
            'Coldplay | The Scientist',
            'Kelis | Milkshake',
            'Gorillaz | Feel Good Inc',
            'Scissor Sisters | Take Your Mama',
            'Alicia Keys | Fallin'
        ],
        indie_pop_crossover: [
            'Lorde | Royals',
            'Lorde | Green Light',
            'Lana Del Rey | Video Games',
            'Lana Del Rey | Summertime Sadness',
            'Robyn | Dancing on My Own',
            'MGMT | Electric Feel',
            'MGMT | Kids',
            'Phoenix | Lisztomania',
            'Gotye | Somebody That I Used to Know',
            'Foster the People | Pumped Up Kicks',
            'Passion Pit | Take a Walk',
            'CHVRCHES | The Mother We Share',
            'Carly Rae Jepsen | Run Away with Me',
            'Grimes | Oblivion',
            'Florence and the Machine | Dog Days Are Over'
        ],
        modern_pop_2010s_2020s: [
            'Taylor Swift | Style',
            'Taylor Swift | Shake It Off',
            'Taylor Swift | Blank Space',
            'Dua Lipa | New Rules',
            'Dua Lipa | Levitating',
            'Dua Lipa | Dont Start Now',
            'Billie Eilish | Bad Guy',
            'Billie Eilish | Ocean Eyes',
            'Harry Styles | As It Was',
            'Harry Styles | Watermelon Sugar',
            'The Weeknd | Blinding Lights',
            'The Weeknd | Save Your Tears',
            'Olivia Rodrigo | Good 4 U',
            'Olivia Rodrigo | Drivers License',
            'Charli XCX | Claws',
            'Doja Cat | Say So',
            'SZA | Kill Bill',
            'Rosalia | Saoko',
            'Bad Bunny | Titi Me Pregunto',
            'Lizzo | Juice',
            'Miley Cyrus | Flowers',
            'Sam Smith | Unholy',
            'Ed Sheeran | Shape of You',
            'Ariana Grande | Into You',
            'Bruno Mars | Uptown Funk'
        ]
    };
    window.genrePopLists = {
        beginner: [
            'ABBA | Dancing Queen',
            'Madonna | Like a Virgin',
            'Whitney Houston | I Wanna Dance with Somebody',
            'Phil Collins | In the Air Tonight',
            'Toto | Africa',
            'Cyndi Lauper | Girls Just Want to Have Fun',
            'George Michael | Faith',
            'Michael Jackson | Billie Jean',
            'Michael Jackson | Thriller',
            'Prince | Purple Rain',
            'A-ha | Take on Me',
            'Bee Gees | Stayin Alive',
            'Elton John | Crocodile Rock',
            'Britney Spears | Baby One More Time',
            'Backstreet Boys | I Want It That Way',
            'Spice Girls | Wannabe',
            'Beyonce | Single Ladies',
            'Rihanna | Umbrella',
            'Ed Sheeran | Shape of You',
            'The Weeknd | Blinding Lights',
            'Taylor Swift | Shake It Off',
            'Adele | Rolling in the Deep',
            'Bruno Mars | Uptown Funk',
            'Lady Gaga | Bad Romance',
            'Dua Lipa | Levitating'
        ],
        intermediate: [
            'Kate Bush | Running Up That Hill',
            'Tears for Fears | Head over Heels',
            'The Human League | Dont You Want Me',
            'Eurythmics | Here Comes the Rain Again',
            'Prefab Sprout | When Love Breaks Down',
            'Robyn | Dancing on My Own',
            'Lorde | Royals',
            'Gotye | Somebody That I Used to Know',
            'Peter Gabriel | Sledgehammer',
            'Sting | Englishman in New York',
            'Annie Lennox | Walking on Broken Glass',
            'Depeche Mode | Enjoy the Silence',
            'Pet Shop Boys | West End Girls',
            'Kylie Minogue | Cant Get You out of My Head',
            'Janet Jackson | Thats the Way Love Goes',
            'TLC | Waterfalls',
            'Mariah Carey | Fantasy',
            'Carly Rae Jepsen | Run Away with Me',
            'CHVRCHES | The Mother We Share',
            'Lana Del Rey | Video Games',
            'Florence and the Machine | Dog Days Are Over',
            'MGMT | Electric Feel',
            'Charli XCX | Brat',
            'Grimes | Oblivion',
            'Nelly Furtado | Say It Right'
        ],
        expert: [
            'Talk Talk | Its My Life',
            'Scritti Politti | Perfect Way',
            'Aztec Camera | Oblivion',
            'The Blue Nile | Tinseltown in the Rain',
            'The The | Uncertain Smile',
            'Japan | Ghosts',
            'China Crisis | Wishful Thinking',
            'Everything but the Girl | Missing',
            'St Etienne | Only Love Can Break Your Heart',
            'Swing Out Sister | Breakout',
            'Level 42 | Something About You',
            'Sade | Smooth Operator',
            'Cocteau Twins | Pearly-Dewdrops Drops',
            'Goldfrapp | Strict Machine',
            'Royksopp | Eple',
            'Moloko | The Time Is Now',
            'Morcheeba | The Sea',
            'Lamb | Gorecki',
            'Jai Paul | Jasmine',
            'Kelela | LMK',
            'FKA Twigs | Water Me',
            'Sampha | Blood on Me',
            'Caroline Polacheck | So Hot You Are Hurting My Feelings',
            'Rina Sawayama | XS',
            'Georgia | About Work the Dancefloor'
        ]
    };
})();
