(function () {
    'use strict';
    window.fallbackPunkSubgenres = {
        proto_punk: [
            'The Stooges | I Wanna Be Your Dog',
            'The Stooges | Search and Destroy',
            'The Stooges | 1970',
            'MC5 | Kick Out the Jams',
            'MC5 | Ramblin Rose',
            'The Velvet Underground | White Light White Heat',
            'The Velvet Underground | Venus in Furs',
            'The Kinks | Till the End of the Day',
            'The Kinks | You Really Got Me',
            'The Sonics | Psycho',
            'The Seeds | Pushin Too Hard',
            'The Troggs | Wild Thing',
            'Alice Cooper | Im Eighteen',
            'Alice Cooper | Schools Out',
            'Television | Marquee Moon',
            'Television | See No Evil',
            'Richard Hell | Blank Generation',
            'New York Dolls | Personality Crisis'
        ],
        first_wave_uk_us: [
            'Ramones | Blitzkrieg Bop',
            'Ramones | Sheena Is a Punk Rocker',
            'Ramones | I Wanna Be Sedated',
            'Sex Pistols | Anarchy in the UK',
            'Sex Pistols | God Save the Queen',
            'Sex Pistols | Pretty Vacant',
            'The Clash | White Riot',
            'The Clash | London Calling',
            'The Clash | Should I Stay or Should I Go',
            'The Damned | New Rose',
            'The Damned | Neat Neat Neat',
            'Buzzcocks | Ever Fallen in Love',
            'Buzzcocks | What Do I Get',
            'Wire | 12XU',
            'Wire | Three Girl Rhumba',
            'X-Ray Spex | Oh Bondage Up Yours',
            'X-Ray Spex | Identity',
            'The Saints | Im Stranded',
            'Stiff Little Fingers | Alternative Ulster',
            'The Undertones | Teenage Kicks'
        ],
        post_punk: [
            'Joy Division | Disorder',
            'Joy Division | Transmission',
            'Joy Division | Love Will Tear Us Apart',
            'Public Image Ltd | Public Image',
            'Public Image Ltd | This Is Not a Love Song',
            'Gang of Four | Damaged Goods',
            'Gang of Four | At Home Hes a Tourist',
            'The Fall | Totally Wired',
            'The Fall | How I Wrote Elastic Man',
            'Wire | Outdoor Miner',
            'Siouxsie and the Banshees | Hong Kong Garden',
            'Siouxsie and the Banshees | Spellbound',
            'Killing Joke | Nervous System',
            'Killing Joke | Eighties',
            'The Cure | A Forest',
            'The Cure | Just Like Heaven',
            'Bauhaus | Bela Lugosis Dead',
            'Bauhaus | She Is in Parties',
            'The Chameleons | Swamp Thing'
        ],
        hardcore_us: [
            'Black Flag | Rise Above',
            'Black Flag | TV Party',
            'Black Flag | My War',
            'Minor Threat | Straight Edge',
            'Minor Threat | In My Eyes',
            'Dead Kennedys | Holiday in Cambodia',
            'Dead Kennedys | California Uber Alles',
            'Dead Kennedys | Too Drunk to Fuck',
            'Bad Brains | Banned in DC',
            'Bad Brains | Sailin On',
            'Circle Jerks | Wild in the Streets',
            'Adolescents | Amoeba',
            'Discharge | Protest and Survive',
            'GBH | City Baby Attacked by Rats',
            'Descendents | Myage',
            'Suicidal Tendencies | Institutionalized',
            'Cro-Mags | World Peace',
            'Agnostic Front | Gotta Go'
        ],
        melodic_punk_90s: [
            'Bad Religion | Generator',
            'Bad Religion | 21st Century Digital Boy',
            'NOFX | Linoleum',
            'NOFX | Bob',
            'Green Day | Longview',
            'Green Day | Basket Case',
            'Green Day | When I Come Around',
            'Rancid | Ruby Soho',
            'Rancid | Time Bomb',
            'Rancid | Roots Radicals',
            'Descendents | Bikeage',
            'Jawbreaker | Accident Prone',
            'Jawbreaker | Boxcar',
            'Samiam | Capsized',
            'The Offspring | Come Out and Play',
            'The Offspring | Self Esteem',
            'Pennywise | Bro Hymn',
            'Lagwagon | May 16',
            'Propagandhi | Anti-Manifesto',
            'Millencolin | No Cigar'
        ],
        emo_post_hardcore: [
            'Fugazi | Waiting Room',
            'Fugazi | Suggestion',
            'Fugazi | Merchandise',
            'At the Drive-In | One Armed Scissor',
            'At the Drive-In | Invalid Litter Dept',
            'Thursday | Understanding in a Car Crash',
            'Refused | New Noise',
            'Refused | Rather Be Dead',
            'Jawbox | Savory',
            'Helmet | Unsung',
            'Helmet | In the Meantime',
            'Quicksand | Fazed',
            'Drive Like Jehu | Yank Crime',
            'Rites of Spring | For Want Of',
            'Sunny Day Real Estate | Seven',
            'The Promise Ring | Why Did Ever We Meet',
            'American Football | Never Meant',
            'Cap n Jazz | Oh Messy Life'
        ],
        punk_2000s_mainstream: [
            'Rise Against | Prayer of the Refugee',
            'Rise Against | Savior',
            'Against Me | Pints of Guinness Make You Strong',
            'Against Me | Thrash Unreal',
            'Alkaline Trio | Radio',
            'Alkaline Trio | Private Eye',
            'NOFX | Franco Un-American',
            'Hot Water Music | Trusty Chords',
            'Anti-Flag | Die for the Government',
            'The Distillers | Drain the Blood',
            'The Distillers | City of Angels',
            'Gaslight Anthem | The 59 Sound',
            'Gaslight Anthem | Great Expectations',
            'The Bouncing Souls | True Believers',
            'The Lawrence Arms | The Devil Wears Prada',
            'Blink-182 | All the Small Things',
            'Blink-182 | Dammit',
            'Sum 41 | Fat Lip',
            'Good Riddance | Mother Superior'
        ],
        modern_punk_revival: [
            'Idles | Never Fight a Man with a Perm',
            'Idles | Mother',
            'Idles | Colossus',
            'Fontaines DC | Boys in the Better Land',
            'Fontaines DC | A Heros Death',
            'Turnstile | Holiday',
            'Turnstile | Mystery',
            'Turnstile | Blackout',
            'Shame | Concrete',
            'Shame | One Rizla',
            'Amyl and the Sniffers | Some Mutts',
            'Amyl and the Sniffers | Hertz',
            'Viagra Boys | Sports',
            'Viagra Boys | Ain\'t Nice',
            'Sleaford Mods | Jobseeker',
            'Sleaford Mods | Tied Up in Nottz',
            'Soft Play | Punks Dead',
            'PUP | If This Tour Doesnt Kill You I Will',
            'Jeff Rosenstock | Nausea',
            'The Chats | Smoko'
        ]
    };
    window.genrePunkLists = {
        beginner: [
            'Ramones | Blitzkrieg Bop',
            'Sex Pistols | Anarchy in the UK',
            'The Clash | London Calling',
            'Green Day | Basket Case',
            'Blink-182 | All the Small Things',
            'Blondie | Heart of Glass',
            'Talking Heads | Psycho Killer',
            'The Offspring | Self Esteem',
            'Green Day | When I Come Around',
            'Ramones | I Wanna Be Sedated',
            'Sex Pistols | God Save the Queen',
            'The Clash | Should I Stay or Should I Go',
            'Dead Kennedys | Holiday in Cambodia',
            'Sum 41 | Fat Lip',
            'Rise Against | Savior',
            'The Stooges | I Wanna Be Your Dog',
            'Rancid | Time Bomb',
            'Pennywise | Bro Hymn',
            'Alice Cooper | Schools Out',
            'Bad Religion | 21st Century Digital Boy',
            'Turnstile | Mystery',
            'The Undertones | Teenage Kicks',
            'Idles | Mother',
            'American Football | Never Meant',
            'Gaslight Anthem | The 59 Sound'
        ],
        intermediate: [
            'The Replacements | Bastards of Young',
            'Husker Du | Makes No Sense at All',
            'The Replacements | Left of the Dial',
            'Fugazi | Waiting Room',
            'Fugazi | Suggestion',
            'Buzzcocks | Ever Fallen in Love',
            'Jawbreaker | Boxcar',
            'Bad Brains | Sailin On',
            'Minor Threat | In My Eyes',
            'Rancid | Ruby Soho',
            'NOFX | Linoleum',
            'At the Drive-In | One Armed Scissor',
            'Refused | New Noise',
            'Descendents | Bikeage',
            'Hot Water Music | Trusty Chords',
            'Against Me | Thrash Unreal',
            'Fontaines DC | Boys in the Better Land',
            'Amyl and the Sniffers | Hertz',
            'Shame | Concrete',
            'PUP | If This Tour Doesnt Kill You I Will',
            'Sunny Day Real Estate | Seven',
            'Thursday | Understanding in a Car Crash',
            'Propagandhi | Anti-Manifesto',
            'The Distillers | Drain the Blood',
            'Joy Division | Transmission'
        ],
        expert: [
            'Wire | 12XU',
            'Television | Marquee Moon',
            'The Stooges | 1970',
            'Wire | Outdoor Miner',
            'Buzzcocks | What Do I Get',
            'Richard Hell | Blank Generation',
            'New York Dolls | Personality Crisis',
            'Stiff Little Fingers | Alternative Ulster',
            'X-Ray Spex | Identity',
            'Gang of Four | Damaged Goods',
            'Killing Joke | Eighties',
            'Drive Like Jehu | Yank Crime',
            'Rites of Spring | For Want Of',
            'Cap n Jazz | Oh Messy Life',
            'Quicksand | Fazed',
            'Helmet | Unsung',
            'MC5 | Kick Out the Jams',
            'Black Flag | My War',
            'Discharge | Protest and Survive',
            'Cro-Mags | World Peace',
            'Sleaford Mods | Tied Up in Nottz',
            'Viagra Boys | Sports',
            'Jeff Rosenstock | Nausea',
            'The Chats | Smoko',
            'Jawbox | Savory'
        ]
    };
})();
