(function () {
    'use strict';
    window.fallbackRnbSoulSubgenres = {
        early_soul_rnb_roots: [
            'Ray Charles | Whatd I Say',
            'Sam Cooke | A Change Is Gonna Come',
            'Sam Cooke | You Send Me',
            'James Brown | Please Please Please',
            'James Brown | I Got You I Feel Good',
            'James Brown | Papa Got a Brand New Bag',
            'Ruth Brown | Mama He Treats Your Daughter Mean',
            'Jackie Wilson | Lonely Teardrops',
            'Jackie Wilson | Higher and Higher',
            'Etta James | At Last',
            'Etta James | I Just Want to Make Love to You',
            'The Drifters | Save the Last Dance for Me',
            'The Drifters | Under the Boardwalk',
            'Ben E King | Stand by Me',
            'Little Richard | Tutti Frutti',
            'Fats Domino | Blueberry Hill',
            'LaVern Baker | Tweedlee Dee',
            'Big Mama Thornton | Hound Dog'
        ],
        motown_classic_soul: [
            'Marvin Gaye | Whats Going On',
            'Marvin Gaye | Lets Get It On',
            'Marvin Gaye | I Heard It Through the Grapevine',
            'The Supremes | You Cant Hurry Love',
            'The Supremes | Baby Love',
            'Stevie Wonder | Signed Sealed Delivered',
            'Stevie Wonder | Superstition',
            'Stevie Wonder | Sir Duke',
            'Smokey Robinson | Tears of a Clown',
            'Smokey Robinson | Tracks of My Tears',
            'The Temptations | My Girl',
            'The Temptations | Just My Imagination',
            'Four Tops | Reach Out Ill Be There',
            'Four Tops | I Cant Help Myself',
            'Martha and the Vandellas | Dancing in the Street',
            'Jackson 5 | I Want You Back',
            'Jackson 5 | ABC',
            'Gladys Knight | Midnight Train to Georgia',
            'The Isley Brothers | Its Your Thing',
            'Edwin Starr | War'
        ],
        deep_soul_funk: [
            'Aretha Franklin | Respect',
            'Aretha Franklin | Natural Woman',
            'Aretha Franklin | Think',
            'Otis Redding | Sittin on the Dock of the Bay',
            'Otis Redding | Try a Little Tenderness',
            'Al Green | Lets Stay Together',
            'Al Green | Tired of Being Alone',
            'Bill Withers | Aint No Sunshine',
            'Bill Withers | Lean on Me',
            'Bill Withers | Lovely Day',
            'Curtis Mayfield | Move on Up',
            'Curtis Mayfield | Superfly',
            'Donny Hathaway | This Christmas',
            'Donny Hathaway | A Song for You',
            'Isaac Hayes | Theme from Shaft',
            'Sly and the Family Stone | Family Affair',
            'Sly and the Family Stone | Everyday People',
            'Bobby Womack | Across 110th Street',
            'Ann Peebles | I Cant Stand the Rain',
            'Minnie Riperton | Lovin You'
        ],
        smooth_soul_70s_80s: [
            'Stevie Wonder | Sir Duke',
            'Earth Wind and Fire | September',
            'Earth Wind and Fire | Fantasy',
            'Earth Wind and Fire | Boogie Wonderland',
            'Luther Vandross | Never Too Much',
            'Luther Vandross | Here and Now',
            'Anita Baker | Sweet Love',
            'Anita Baker | Giving You the Best That I Got',
            'Lionel Richie | Hello',
            'Lionel Richie | All Night Long',
            'Chaka Khan | Aint Nobody',
            'Chaka Khan | Im Every Woman',
            'Prince | When Doves Cry',
            'Prince | Kiss',
            'Michael Jackson | Off the Wall',
            'Michael Jackson | Rock with You',
            'Whitney Houston | Greatest Love of All',
            'Whitney Houston | I Wanna Dance with Somebody',
            'Teddy Pendergrass | Love TKO',
            'The Whispers | Rock Steady'
        ],
        new_jack_swing_early_rnb: [
            'Janet Jackson | Thats the Way Love Goes',
            'Janet Jackson | Nasty',
            'Janet Jackson | Rhythm Nation',
            'Bobby Brown | My Prerogative',
            'Bobby Brown | Every Little Step',
            'Bell Biv DeVoe | Poison',
            'Guy | Groove Me',
            'Keith Sweat | I Want Her',
            'New Edition | Can You Stand the Rain',
            'New Edition | If It Isnt Love',
            'Toni Braxton | Breathe Again',
            'Toni Braxton | Un-Break My Heart',
            'Mary J Blige | Real Love',
            'Mary J Blige | No More Drama',
            'TLC | Waterfalls',
            'TLC | No Scrubs',
            'En Vogue | My Lovin',
            'SWV | Weak',
            'Boyz II Men | End of the Road',
            'R Kelly | I Believe I Can Fly'
        ],
        neo_soul_90s: [
            'DAngelo | Brown Sugar',
            'DAngelo | Untitled How Does It Feel',
            'Erykah Badu | On and On',
            'Erykah Badu | Tyrone',
            'Erykah Badu | Bag Lady',
            'Lauryn Hill | Doo Wop That Thing',
            'Lauryn Hill | Everything Is Everything',
            'Maxwell | Ascension',
            'Maxwell | This Womans Work',
            'Jill Scott | A Long Walk',
            'Jill Scott | Golden',
            'Mos Def | Ms Fat Booty',
            'The Roots | You Got Me',
            'India Arie | Video',
            'Musiq Soulchild | Just Friends',
            'Anthony Hamilton | Charlene',
            'Angie Stone | No More Rain',
            'Bilal | Soul Sista'
        ],
        '2000s_rnb_pop_crossover': [
            'Alicia Keys | Fallin',
            'Alicia Keys | No One',
            'Alicia Keys | If I Aint Got You',
            'Usher | U Got It Bad',
            'Usher | Yeah',
            'Usher | Burn',
            'Beyonce | Crazy in Love',
            'Beyonce | Single Ladies',
            'Beyonce | Irreplaceable',
            'Destinys Child | Say My Name',
            'Destinys Child | Jumpin Jumpin',
            'Ne-Yo | So Sick',
            'Ne-Yo | Miss Independent',
            'John Legend | Ordinary People',
            'John Legend | All of Me',
            'Rihanna | Umbrella',
            'Rihanna | We Found Love',
            'Justin Timberlake | Cry Me a River',
            'Justin Timberlake | Rock Your Body',
            'Chris Brown | With You',
            'Akon | Dont Matter',
            'Mario | Let Me Love You'
        ],
        modern_alt_rnb: [
            'Frank Ocean | Thinkin Bout You',
            'Frank Ocean | Nights',
            'Frank Ocean | Pyramids',
            'Frank Ocean | Self Control',
            'The Weeknd | Wicked Games',
            'The Weeknd | Blinding Lights',
            'The Weeknd | Save Your Tears',
            'Miguel | Adorn',
            'Miguel | Sure Thing',
            'Solange | Cranes in the Sky',
            'Solange | Losing You',
            'SZA | Love Galore',
            'SZA | Kill Bill',
            'SZA | Good Days',
            'James Blake | Retrograde',
            'James Blake | Limit to Your Love',
            'Sampha | Blood on Me',
            'Sampha | Process',
            'Jhene Aiko | The Worst',
            'Kelela | LMK',
            'FKA Twigs | Water Me',
            'FKA Twigs | Cellophane'
        ],
        contemporary_soul_future_rnb: [
            'H.E.R. | Focus',
            'H.E.R. | Best Part',
            'Daniel Caesar | Get You',
            'Daniel Caesar | Best Part',
            'Anderson Paak | Am I Wrong',
            'Anderson Paak | Come Down',
            'Anderson Paak | Tints',
            'Summer Walker | Girls Need Love',
            'Summer Walker | Playing Games',
            'Cleo Sol | Why Dont You',
            'Cleo Sol | When Im in Your Arms',
            'Lucky Daye | Roll Some Mo',
            'Jazmine Sullivan | Lost One',
            'Jazmine Sullivan | Pick Up Your Feelings',
            'Snoh Aalegra | I Want You Around',
            'Snoh Aalegra | Whoa',
            'Giveon | Heartbreak Anniversary',
            'Steve Lacy | Bad Habit',
            'Victoria Monet | On My Mama',
            'Brent Faiyaz | Wasting Time'
        ]
    };
    window.genreRnbSoulLists = {
        beginner: [
            'Stevie Wonder | Superstition',
            'Marvin Gaye | Lets Get It On',
            'Aretha Franklin | Respect',
            'Lionel Richie | All Night Long',
            'Beyonce | Crazy in Love',
            'Usher | Yeah',
            'Al Green | Lets Stay Together',
            'Whitney Houston | I Wanna Dance with Somebody',
            'Michael Jackson | Billie Jean',
            'Earth Wind and Fire | September',
            'Prince | Kiss',
            'Bill Withers | Lean on Me',
            'TLC | No Scrubs',
            'Boyz II Men | End of the Road',
            'Rihanna | Umbrella',
            'Alicia Keys | Fallin',
            'John Legend | All of Me',
            'The Weeknd | Blinding Lights',
            'SZA | Kill Bill',
            'Jackson 5 | I Want You Back',
            'Ben E King | Stand by Me',
            'Sam Cooke | A Change Is Gonna Come',
            'Toni Braxton | Un-Break My Heart',
            'Justin Timberlake | Rock Your Body',
            'Mary J Blige | No More Drama'
        ],
        intermediate: [
            'Sade | Smooth Operator',
            'Janet Jackson | Thats the Way Love Goes',
            'Maxwell | Ascension',
            'DAngelo | Brown Sugar',
            'Erykah Badu | On and On',
            'Lauryn Hill | Everything Is Everything',
            'Jill Scott | A Long Walk',
            'Frank Ocean | Thinkin Bout You',
            'Solange | Cranes in the Sky',
            'Curtis Mayfield | Move on Up',
            'Bobby Womack | Across 110th Street',
            'Chaka Khan | Im Every Woman',
            'Luther Vandross | Never Too Much',
            'Anita Baker | Sweet Love',
            'India Arie | Video',
            'Miguel | Adorn',
            'Anderson Paak | Come Down',
            'Daniel Caesar | Get You',
            'Gladys Knight | Midnight Train to Georgia',
            'New Edition | Can You Stand the Rain',
            'SWV | Weak',
            'Musiq Soulchild | Just Friends',
            'Steve Lacy | Bad Habit',
            'Summer Walker | Girls Need Love',
            'Ne-Yo | So Sick'
        ],
        expert: [
            'Donny Hathaway | A Song for You',
            'Minnie Riperton | Lovin You',
            'DAngelo | Untitled How Does It Feel',
            'Maxwell | This Womans Work',
            'Bilal | Soul Sista',
            'Anthony Hamilton | Charlene',
            'Angie Stone | No More Rain',
            'Ann Peebles | I Cant Stand the Rain',
            'Teddy Pendergrass | Love TKO',
            'The Whispers | Rock Steady',
            'Roy Ayers | Everybody Loves the Sunshine',
            'Terry Callier | Ordinary Joe',
            'Gil Scott-Heron | The Revolution Will Not Be Televised',
            'Betty Davis | They Say Im Different',
            'Kelela | LMK',
            'FKA Twigs | Cellophane',
            'Sampha | Process',
            'James Blake | Limit to Your Love',
            'Cleo Sol | When Im in Your Arms',
            'Brent Faiyaz | Wasting Time',
            'Lucky Daye | Roll Some Mo',
            'Jazmine Sullivan | Pick Up Your Feelings',
            'Giveon | Heartbreak Anniversary',
            'Victoria Monet | On My Mama',
            'Snoh Aalegra | Whoa'
        ]
    };
})();
