(function () {
    'use strict';
    window.fallbackRockSubgenres = {
        classic_rock_50s_60s: [
            'Chuck Berry | Johnny B. Goode',
            'Little Richard | Tutti Frutti',
            'Elvis Presley | Hound Dog',
            'Buddy Holly | Peggy Sue',
            'The Beatles | Helter Skelter',
            'The Rolling Stones | Gimme Shelter',
            'The Who | My Generation',
            'The Kinks | You Really Got Me',
            'Cream | Sunshine of Your Love',
            'Jimi Hendrix | Purple Haze',
            'The Doors | Break on Through',
            'The Velvet Underground | Venus in Furs'
        ],
        classic_rock_70s: [
            'Led Zeppelin | Whole Lotta Love',
            'Led Zeppelin | Kashmir',
            'David Bowie | Heroes',
            'David Bowie | Ziggy Stardust',
            'Pink Floyd | Time',
            'Pink Floyd | Money',
            'Queen | Stone Cold Crazy',
            'Queen | Somebody to Love',
            'Black Sabbath | Paranoid',
            'Neil Young | Cortez the Killer',
            'Iggy Pop | Lust for Life',
            'Fleetwood Mac | The Chain',
            'Deep Purple | Smoke on the Water',
            'Thin Lizzy | The Boys Are Back in Town',
            'Boston | More Than a Feeling',
            'Lynyrd Skynyrd | Free Bird',
            'Aerosmith | Walk This Way',
            'Styx | Come Sail Away',
            'Kansas | Carry On Wayward Son',
            'ZZ Top | La Grange'
        ],
        prog_rock: [
            'Yes | Roundabout',
            'Genesis | The Lamb Lies Down on Broadway',
            'King Crimson | 21st Century Schizoid Man',
            'Emerson Lake & Palmer | Lucky Man',
            'Jethro Tull | Aqualung',
            'Rush | Tom Sawyer',
            'Rush | The Spirit of Radio',
            'Camel | Lady Fantasy',
            'Gentle Giant | The Power and the Glory',
            'Porcupine Tree | Trains',
            'Tool | Schism',
            'Mars Volta | Inertiatic ESP'
        ],
        post_punk_new_wave: [
            'Joy Division | Transmission',
            'Joy Division | Love Will Tear Us Apart',
            'The Cure | Boys Dont Cry',
            'The Cure | Just Like Heaven',
            'U2 | I Will Follow',
            'Talking Heads | Once in a Lifetime',
            'Talking Heads | Psycho Killer',
            'The Police | Message in a Bottle',
            'Echo and the Bunnymen | The Killing Moon',
            'Siouxsie and the Banshees | Spellbound',
            'The Fall | Totally Wired',
            'Wire | Outdoor Miner',
            'Gang of Four | Damaged Goods',
            'Bauhaus | Bela Lugosis Dead',
            'The Smiths | This Charming Man',
            'New Order | Blue Monday',
            'Depeche Mode | Personal Jesus',
            'The Chameleons | Swamp Thing'
        ],
        arena_rock_80s: [
            'Bon Jovi | Livin on a Prayer',
            'Def Leppard | Pour Some Sugar on Me',
            'Journey | Dont Stop Believin',
            'Foreigner | I Want to Know What Love Is',
            'Dire Straits | Money for Nothing',
            'Dire Straits | Sultans of Swing',
            'Bruce Springsteen | Born in the U.S.A.',
            'Bruce Springsteen | Born to Run',
            'Bryan Adams | Summer of 69',
            'John Mellencamp | Jack and Diane',
            'Tom Petty | Free Fallin',
            'Tom Petty | American Girl',
            'The Cars | Just What I Needed',
            'Pat Benatar | Hit Me with Your Best Shot',
            'Heart | Barracuda',
            'REO Speedwagon | Keep On Loving You'
        ],
        grunge_alternative_90s: [
            'Nirvana | In Bloom',
            'Nirvana | Come as You Are',
            'Nirvana | Heart-Shaped Box',
            'Radiohead | Fake Plastic Trees',
            'Radiohead | Paranoid Android',
            'Pearl Jam | Alive',
            'Pearl Jam | Even Flow',
            'Soundgarden | Black Hole Sun',
            'Smashing Pumpkins | Cherub Rock',
            'Smashing Pumpkins | 1979',
            'Stone Temple Pilots | Plush',
            'Alice in Chains | Would',
            'Alice in Chains | Rooster',
            'Rage Against the Machine | Killing in the Name',
            'Weezer | Buddy Holly',
            'Weezer | Say It Aint So',
            'Bush | Glycerine',
            'Silverchair | Tomorrow',
            'Live | Lightning Crashes',
            'Collective Soul | Shine'
        ],
        britpop: [
            'Oasis | Wonderwall',
            'Oasis | Live Forever',
            'Blur | Song 2',
            'Blur | Parklife',
            'Pulp | Common People',
            'Suede | Beautiful Ones',
            'Elastica | Connection',
            'Supergrass | Alright',
            'Manic Street Preachers | A Design for Life',
            'The Verve | Bitter Sweet Symphony',
            'Travis | Why Does It Always Rain on Me',
            'Stereophonics | Dakota'
        ],
        rock_2000s: [
            'The Strokes | Last Nite',
            'The Strokes | Reptilia',
            'The White Stripes | Seven Nation Army',
            'Queens of the Stone Age | No One Knows',
            'Foo Fighters | Everlong',
            'Foo Fighters | The Pretender',
            'Muse | Hysteria',
            'Muse | Supermassive Black Hole',
            'The Killers | Mr. Brightside',
            'Franz Ferdinand | Take Me Out',
            'Bloc Party | Helicopter',
            'Interpol | Obstacle 1',
            'Kings of Leon | Sex on Fire',
            'Jimmy Eat World | The Middle',
            'Audioslave | Like a Stone',
            'System of a Down | Chop Suey'
        ],
        modern_rock_2010s_2020s: [
            'Arctic Monkeys | Do I Wanna Know',
            'Arctic Monkeys | R U Mine',
            'Tame Impala | Elephant',
            'Tame Impala | The Less I Know the Better',
            'The National | Bloodbuzz Ohio',
            'The Black Keys | Lonely Boy',
            'The Black Keys | Gold on the Ceiling',
            'Royal Blood | Figure It Out',
            'Idles | Mother',
            'Fontaines DC | I Dont Belong',
            'Fontaines DC | Boys in the Better Land',
            'Wet Leg | Chaise Longue',
            'Turnstile | Mystery',
            'Greta Van Fleet | Highway Tune',
            'Nothing But Thieves | Amsterdam',
            'Wolf Alice | Dont Delete the Kisses',
            'Courtney Barnett | Pedestrian at Best',
            'Amyl and the Sniffers | Hertz',
            'King Gizzard | Rattlesnake',
            'Black Midi | John L'
        ]
    };
    window.genreRockLists = {
        beginner: [
            'Queen | Bohemian Rhapsody',
            'Led Zeppelin | Stairway to Heaven',
            'AC/DC | Back in Black',
            'AC/DC | Highway to Hell',
            'Eagles | Hotel California',
            'Guns N Roses | Sweet Child O Mine',
            'Bon Jovi | Livin on a Prayer',
            'Journey | Dont Stop Believin',
            'Nirvana | Smells Like Teen Spirit',
            'The Rolling Stones | Satisfaction',
            'Deep Purple | Smoke on the Water',
            'Aerosmith | I Dont Want to Miss a Thing',
            'The Beatles | Come Together',
            'The Beatles | Let It Be',
            'U2 | With or Without You',
            'Red Hot Chili Peppers | Californication',
            'Red Hot Chili Peppers | Under the Bridge',
            'Oasis | Wonderwall',
            'Foo Fighters | Everlong',
            'The White Stripes | Seven Nation Army',
            'Lynyrd Skynyrd | Sweet Home Alabama',
            'Fleetwood Mac | Dreams',
            'David Bowie | Let's Dance',
            'Pink Floyd | Comfortably Numb',
            'Bruce Springsteen | Born in the U.S.A.'
        ],
        intermediate: [
            'The Smiths | How Soon Is Now',
            'Pixies | Where Is My Mind',
            'Fleetwood Mac | The Chain',
            'The Cure | Just Like Heaven',
            'Radiohead | Creep',
            'Radiohead | No Surprises',
            'Pearl Jam | Black',
            'Soundgarden | Black Hole Sun',
            'Talking Heads | Once in a Lifetime',
            'Tom Petty | Free Fallin',
            'Dire Straits | Sultans of Swing',
            'Smashing Pumpkins | 1979',
            'Weezer | Buddy Holly',
            'Muse | Supermassive Black Hole',
            'Kings of Leon | Sex on Fire',
            'The Verve | Bitter Sweet Symphony',
            'Stone Temple Pilots | Interstate Love Song',
            'Alice in Chains | Down in a Hole',
            'The Cranberries | Zombie',
            'Blur | Song 2',
            'Franz Ferdinand | Take Me Out',
            'Arctic Monkeys | I Bet You Look Good on the Dancefloor',
            'The Killers | Mr. Brightside',
            'Queens of the Stone Age | No One Knows',
            'Interpol | Obstacle 1'
        ],
        expert: [
            'New Order | Bizarre Love Triangle',
            'The Jesus and Mary Chain | Just Like Honey',
            'Echo and the Bunnymen | The Killing Moon',
            'The Church | Under the Milky Way',
            'The Replacements | Left of the Dial',
            'Cocteau Twins | Cherry-Coloured Funk',
            'Wire | Pink Flag',
            'Siouxsie and the Banshees | Cities in Dust',
            'Bauhaus | She Is in Parties',
            'The Chameleons | Swamp Thing',
            'Television | Marquee Moon',
            'Husker Du | Makes No Sense at All',
            'Dinosaur Jr | Freak Scene',
            'Sonic Youth | Teenage Riot',
            'Pavement | Gold Soundz',
            'Guided by Voices | I Am a Scientist',
            'Built to Spill | Carry the Zero',
            'Modest Mouse | Trailer Trash',
            'Porcupine Tree | Trains',
            'Ride | Vapour Trail',
            'Slowdive | Alison',
            'My Bloody Valentine | Only Shallow',
            'Slint | Good Morning Captain',
            'The Fall | How I Wrote Elastic Man',
            'Gang of Four | Damaged Goods'
        ]
    };
})();
