(function () {
    'use strict';
    window.fallbackTechnoSubgenres = {
        proto_techno_electro: [
            'Kraftwerk | Numbers',
            'Kraftwerk | Trans-Europe Express',
            'Kraftwerk | Computer Love',
            'Cybotron | Clear',
            'Cybotron | Alleys of Your Mind',
            'Afrika Bambaataa | Planet Rock',
            'Model 500 | No UFOs',
            'Model 500 | Night Drive',
            'Hashim | Al Naafiysh',
            'Newcleus | Jam on It',
            'The Egyptian Lover | Egypt Egypt',
            'Drexciya | Aqua Worm Hole',
            'Aux 88 | Bass Magnetic',
            'Man Parrish | Hip Hop Be Bop'
        ],
        detroit_first_wave: [
            'Juan Atkins | Techno City',
            'Derrick May | Strings of Life',
            'Derrick May | Nude Photo',
            'Kevin Saunderson | Big Fun',
            'Kevin Saunderson | Good Life',
            'Inner City | Good Life',
            'Inner City | Big Fun',
            'Rhythim Is Rhythim | Strings of Life',
            'Model 500 | Night Drive',
            'Eddie Fowlkes | Goodbye Kiss',
            'Blake Baxter | When a Thought Becomes You',
            'Octave One | Blackwater',
            'Carl Craig | Bug in the Bassbin',
            'Kenny Larkin | Azimuth',
            'Stacey Pullen | Bango',
            'Jeff Mills | The Bells'
        ],
        early_rave_hardcore: [
            'Joey Beltram | Energy Flash',
            'Joey Beltram | Mentasm',
            'LFO | LFO',
            'LFO | Frequencies',
            'Altern 8 | Activ 8',
            'The Prodigy | Charly',
            'The Prodigy | Everybody in the Place',
            '2 Bad Mice | Bomb Scare',
            'The Future Sound of London | Papua New Guinea',
            'The Future Sound of London | Cascade',
            'Speedy J | Pullover',
            'Dave Angel | Airborne',
            'Second Phase | Mentasm',
            'Human Resource | Dominator',
            'T99 | Anasthasia',
            'LA Style | James Brown Is Dead'
        ],
        uk_techno_early_90s: [
            'Orbital | Chime',
            'Orbital | Halcyon',
            'Orbital | Belfast',
            'Underworld | Dark and Long',
            'Underworld | Born Slippy',
            'Underworld | Cowgirl',
            'Leftfield | Not Forgotten',
            'Leftfield | Phat Planet',
            'The Sabres of Paradise | Smokebelch II',
            '808 State | Pacific State',
            '808 State | Cubik',
            'B12 | Electro Soma',
            'Autechre | Egg Shell',
            'Luke Slater | Love',
            'Aphex Twin | Didgeridoo',
            'The Black Dog | Parallel Squelch',
            'Global Communication | 14 31'
        ],
        minimal_acid_90s: [
            'Plastikman | Spastik',
            'Plastikman | Consumed',
            'Hardfloor | Acperience 1',
            'DBX | Losing Control',
            'Basic Channel | Phylyps Trak',
            'Basic Channel | Quadrant Dub',
            'Aphex Twin | Didgeridoo',
            'Richie Hawtin | Orange Minus',
            'CJ Bolland | Camargue',
            'Robert Hood | Minimal Nation',
            'Robert Hood | Internal Empire',
            'Phuture | Acid Tracks',
            'Josh Wink | Higher State of Consciousness',
            'DJ Pierre | Acid Tracks',
            'Adonis | No Way Back',
            'Armando | 151'
        ],
        berlin_berghain_roots: [
            'Surgeon | Badger Bite',
            'Surgeon | Magneze',
            'Regis | Execution',
            'Jeff Mills | The Bells',
            'Jeff Mills | Phase 4',
            'Dave Clarke | Wisdom to the Wise',
            'Dave Clarke | Red 3',
            'Ben Sims | Manipulate',
            'Adam Beyer | Drumcode 1',
            'Chris Liebing | Stigmata',
            'Luke Slater | Love',
            'Oliver Ho | Unsettled',
            'Oscar Mulero | Tren de Cercania',
            'Cari Lekebusch | Klansen',
            'Gaetek | Drumming'
        ],
        techno_2000s_peak: [
            'Ben Klock | Subzero',
            'Ben Klock | Before One',
            'Marcel Dettmann | Corebox',
            'Marcel Dettmann | Translation',
            'Len Faki | Just a Dance',
            'Len Faki | Mekong Delta',
            'Extrawelt | Soopertrack',
            'Trentemoller | Moan',
            'Trentemoller | Miss You',
            'Paul Kalkbrenner | Aaron',
            'Paul Kalkbrenner | Sky and Sand',
            'Dubfire | Ribcage',
            'Pan-Pot | Captivate',
            'Pan-Pot | Confronted',
            'Stephan Bodzin | Powers of Ten',
            'Maceo Plex | Solar Detroit'
        ],
        dub_ambient_techno: [
            'Basic Channel | Quadrant Dub',
            'Basic Channel | Phylyps Trak II',
            'Deepchord | DC11',
            'Deepchord | Hash Bar Loops',
            'Porter Ricks | Biokinetics',
            'Porter Ricks | Nautical Dub',
            'Rhythm and Sound | Never Tell You',
            'Rhythm and Sound | Mango Drive',
            'Monolake | Cyan',
            'Monolake | Ghosts',
            'Gas | Konigsforst',
            'Gas | Pop',
            'Barker | Utility',
            'Fluxion | Vibrant Forms',
            'Vladislav Delay | Anima',
            'Wolfgang Voigt | Freiland Klaviermusik'
        ],
        modern_industrial_techno: [
            'Paula Temple | Colonized',
            'Paula Temple | Deathvox',
            'Ansome | Blackwater',
            'Ansome | Stowaway',
            'Blawan | Why They Hide Their Bodies Under My Garage',
            'Blawan | Getting Me Down',
            'Karenn | Pace Yourself',
            'SNTS | Es Ist Nichts',
            'Rebekah | Code Black',
            'Rebekah | Fear Passing',
            'Ancient Methods | Knights and Bishops',
            'Perc | Look What Your Love Has Done to Me',
            'Perc | Bitter Pills',
            'Headless Horseman | Headless Horseman 005',
            'AnD | Outer Limits',
            'Boston 168 | Interstellar'
        ],
        modern_hypnotic_techno: [
            'Rene Wise | Movers',
            'Rodhad | Kinder der Ringwelt',
            'Donato Dozzy | Vaporware',
            'Donato Dozzy | Voices from the Lake',
            'NTHNG | It Never Ends',
            'Oscar Mulero | Second Skin',
            'Shifted | Control',
            'Planetary Assault Systems | Rip the Cut',
            'Planetary Assault Systems | In from the Night',
            'Jane Fitz | Wild Flower',
            'Dasha Rush | Sleepstep',
            'Varg | Nordic Flora',
            'Shxcxchcxsh | SsSsSsSsSsSsSsSsSsSsSs',
            'Etapp Kyle | Alpha',
            'Dax J | Offending Public Morality'
        ],
        new_rave_post_techno: [
            'Charlotte de Witte | Selected',
            'Charlotte de Witte | Doppler',
            'Amelie Lens | Stay with Me',
            'Amelie Lens | Access',
            'I Hate Models | Daydream',
            'I Hate Models | Warehouse Memories',
            'Kobosil | 110 BPM',
            'VTSS | Body Count',
            'VTSS | Ambush',
            'FJAAK | Drugs',
            'FJAAK | On',
            'Overmono | So U Kno',
            'Overmono | Everything U Need',
            'Bicep | Glue',
            'Bicep | Atlas',
            'HAAi | Be Good',
            'Hector Oaks | Strength and Honour',
            '999999999 | Mineral Extraction'
        ]
    };
    window.genreTechnoLists = {
        beginner: [
            'Underworld | Born Slippy',
            'Orbital | Halcyon',
            'Leftfield | Phat Planet',
            'The Prodigy | Everybody in the Place',
            'Faithless | Insomnia',
            'Joey Beltram | Energy Flash',
            'Derrick May | Strings of Life',
            'Paul Kalkbrenner | Sky and Sand',
            'Afrika Bambaataa | Planet Rock',
            'CJ Bolland | Camargue',
            'Inner City | Good Life',
            '808 State | Pacific State',
            'Kraftwerk | Trans-Europe Express',
            'LFO | LFO',
            'Bicep | Glue',
            'Overmono | So U Kno',
            'Charlotte de Witte | Selected',
            'The Future Sound of London | Papua New Guinea',
            'Josh Wink | Higher State of Consciousness',
            'Human Resource | Dominator',
            'Trentemoller | Moan',
            'Octave One | Blackwater',
            'Amelie Lens | Stay with Me',
            'Paul Kalkbrenner | Aaron',
            'Orbital | Chime'
        ],
        intermediate: [
            'Underworld | Dark and Long',
            'Jeff Mills | The Bells',
            'Leftfield | Not Forgotten',
            'Plastikman | Spastik',
            'DJ Rolando | Knights of the Jaguar',
            'Second Phase | Mentasm',
            'Surgeon | Magneze',
            'Ken Ishii | Extra',
            'Dave Clarke | Red 3',
            'Model 500 | No UFOs',
            'Carl Craig | Bug in the Bassbin',
            'Ben Klock | Before One',
            'Marcel Dettmann | Translation',
            'Stephan Bodzin | Powers of Ten',
            'Robert Hood | Minimal Nation',
            'Phuture | Acid Tracks',
            'Drexciya | Aqua Worm Hole',
            'Kenny Larkin | Azimuth',
            'I Hate Models | Daydream',
            'Hardfloor | Acperience 1',
            'Gas | Pop',
            'Pan-Pot | Captivate',
            'Extrawelt | Soopertrack',
            'FJAAK | Drugs',
            'Monolake | Cyan'
        ],
        expert: [
            'Regis | Execution',
            'Surgeon | Badger Bite',
            'Ben Klock | Subzero',
            'Marcel Dettmann | Corebox',
            'Blawan | Why They Hide Their Bodies Under My Garage',
            'Paula Temple | Colonized',
            'I Hate Models | Warehouse Memories',
            'Basic Channel | Quadrant Dub',
            'Porter Ricks | Biokinetics',
            'Rhythm and Sound | Never Tell You',
            'Deepchord | Hash Bar Loops',
            'Oscar Mulero | Second Skin',
            'Donato Dozzy | Voices from the Lake',
            'Planetary Assault Systems | Rip the Cut',
            'Ancient Methods | Knights and Bishops',
            'Perc | Bitter Pills',
            'SNTS | Es Ist Nichts',
            'Shifted | Control',
            'Vladislav Delay | Anima',
            'Shxcxchcxsh | SsSsSsSsSsSsSsSsSsSsSs',
            'VTSS | Body Count',
            'Kobosil | 110 BPM',
            'Dax J | Offending Public Morality',
            'Etapp Kyle | Alpha',
            '999999999 | Mineral Extraction'
        ]
    };
})();
